// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mbr-bid.proto

package eu.m6r.format.openrtb;

public final class MbrBid {
  private MbrBid() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface JoinedBidOrBuilder extends
      // @@protoc_insertion_point(interface_extends:eu.m6r.format.openrtb.JoinedBid)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
     *
     * <pre>
     * Mbr: mbr-bid-request.proto.
     * </pre>
     */
    boolean hasBidrequest();
    /**
     * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
     *
     * <pre>
     * Mbr: mbr-bid-request.proto.
     * </pre>
     */
    com.google.openrtb.OpenRtb.BidRequest getBidrequest();
    /**
     * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
     *
     * <pre>
     * Mbr: mbr-bid-request.proto.
     * </pre>
     */
    com.google.openrtb.OpenRtb.BidRequestOrBuilder getBidrequestOrBuilder();

    /**
     * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
     *
     * <pre>
     * Mbr: mbr-bid-response.proto.
     * </pre>
     */
    boolean hasBidresponse();
    /**
     * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
     *
     * <pre>
     * Mbr: mbr-bid-response.proto.
     * </pre>
     */
    com.google.openrtb.OpenRtb.BidResponse getBidresponse();
    /**
     * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
     *
     * <pre>
     * Mbr: mbr-bid-response.proto.
     * </pre>
     */
    com.google.openrtb.OpenRtb.BidResponseOrBuilder getBidresponseOrBuilder();
  }
  /**
   * Protobuf type {@code eu.m6r.format.openrtb.JoinedBid}
   *
   * <pre>
   * Mbr: BidRequest and BidResponse together.
   * </pre>
   */
  public static final class JoinedBid extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:eu.m6r.format.openrtb.JoinedBid)
      JoinedBidOrBuilder {
    // Use JoinedBid.newBuilder() to construct.
    private JoinedBid(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private JoinedBid(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final JoinedBid defaultInstance;
    public static JoinedBid getDefaultInstance() {
      return defaultInstance;
    }

    public JoinedBid getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private JoinedBid(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.openrtb.OpenRtb.BidRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = bidrequest_.toBuilder();
              }
              bidrequest_ = input.readMessage(com.google.openrtb.OpenRtb.BidRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bidrequest_);
                bidrequest_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.google.openrtb.OpenRtb.BidResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = bidresponse_.toBuilder();
              }
              bidresponse_ = input.readMessage(com.google.openrtb.OpenRtb.BidResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bidresponse_);
                bidresponse_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.m6r.format.openrtb.MbrBid.internal_static_eu_m6r_format_openrtb_JoinedBid_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.m6r.format.openrtb.MbrBid.internal_static_eu_m6r_format_openrtb_JoinedBid_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.m6r.format.openrtb.MbrBid.JoinedBid.class, eu.m6r.format.openrtb.MbrBid.JoinedBid.Builder.class);
    }

    public static com.google.protobuf.Parser<JoinedBid> PARSER =
        new com.google.protobuf.AbstractParser<JoinedBid>() {
      public JoinedBid parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JoinedBid(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<JoinedBid> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BIDREQUEST_FIELD_NUMBER = 1;
    private com.google.openrtb.OpenRtb.BidRequest bidrequest_;
    /**
     * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
     *
     * <pre>
     * Mbr: mbr-bid-request.proto.
     * </pre>
     */
    public boolean hasBidrequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
     *
     * <pre>
     * Mbr: mbr-bid-request.proto.
     * </pre>
     */
    public com.google.openrtb.OpenRtb.BidRequest getBidrequest() {
      return bidrequest_;
    }
    /**
     * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
     *
     * <pre>
     * Mbr: mbr-bid-request.proto.
     * </pre>
     */
    public com.google.openrtb.OpenRtb.BidRequestOrBuilder getBidrequestOrBuilder() {
      return bidrequest_;
    }

    public static final int BIDRESPONSE_FIELD_NUMBER = 2;
    private com.google.openrtb.OpenRtb.BidResponse bidresponse_;
    /**
     * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
     *
     * <pre>
     * Mbr: mbr-bid-response.proto.
     * </pre>
     */
    public boolean hasBidresponse() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
     *
     * <pre>
     * Mbr: mbr-bid-response.proto.
     * </pre>
     */
    public com.google.openrtb.OpenRtb.BidResponse getBidresponse() {
      return bidresponse_;
    }
    /**
     * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
     *
     * <pre>
     * Mbr: mbr-bid-response.proto.
     * </pre>
     */
    public com.google.openrtb.OpenRtb.BidResponseOrBuilder getBidresponseOrBuilder() {
      return bidresponse_;
    }

    private void initFields() {
      bidrequest_ = com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance();
      bidresponse_ = com.google.openrtb.OpenRtb.BidResponse.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasBidrequest()) {
        if (!getBidrequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasBidresponse()) {
        if (!getBidresponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, bidrequest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, bidresponse_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, bidrequest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, bidresponse_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static eu.m6r.format.openrtb.MbrBid.JoinedBid parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.m6r.format.openrtb.MbrBid.JoinedBid parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.m6r.format.openrtb.MbrBid.JoinedBid parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.m6r.format.openrtb.MbrBid.JoinedBid parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.m6r.format.openrtb.MbrBid.JoinedBid parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.m6r.format.openrtb.MbrBid.JoinedBid parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static eu.m6r.format.openrtb.MbrBid.JoinedBid parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static eu.m6r.format.openrtb.MbrBid.JoinedBid parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static eu.m6r.format.openrtb.MbrBid.JoinedBid parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.m6r.format.openrtb.MbrBid.JoinedBid parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.m6r.format.openrtb.MbrBid.JoinedBid prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eu.m6r.format.openrtb.JoinedBid}
     *
     * <pre>
     * Mbr: BidRequest and BidResponse together.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:eu.m6r.format.openrtb.JoinedBid)
        eu.m6r.format.openrtb.MbrBid.JoinedBidOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.m6r.format.openrtb.MbrBid.internal_static_eu_m6r_format_openrtb_JoinedBid_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.m6r.format.openrtb.MbrBid.internal_static_eu_m6r_format_openrtb_JoinedBid_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eu.m6r.format.openrtb.MbrBid.JoinedBid.class, eu.m6r.format.openrtb.MbrBid.JoinedBid.Builder.class);
      }

      // Construct using eu.m6r.format.openrtb.MbrBid.JoinedBid.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBidrequestFieldBuilder();
          getBidresponseFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (bidrequestBuilder_ == null) {
          bidrequest_ = com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance();
        } else {
          bidrequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (bidresponseBuilder_ == null) {
          bidresponse_ = com.google.openrtb.OpenRtb.BidResponse.getDefaultInstance();
        } else {
          bidresponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.m6r.format.openrtb.MbrBid.internal_static_eu_m6r_format_openrtb_JoinedBid_descriptor;
      }

      public eu.m6r.format.openrtb.MbrBid.JoinedBid getDefaultInstanceForType() {
        return eu.m6r.format.openrtb.MbrBid.JoinedBid.getDefaultInstance();
      }

      public eu.m6r.format.openrtb.MbrBid.JoinedBid build() {
        eu.m6r.format.openrtb.MbrBid.JoinedBid result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public eu.m6r.format.openrtb.MbrBid.JoinedBid buildPartial() {
        eu.m6r.format.openrtb.MbrBid.JoinedBid result = new eu.m6r.format.openrtb.MbrBid.JoinedBid(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (bidrequestBuilder_ == null) {
          result.bidrequest_ = bidrequest_;
        } else {
          result.bidrequest_ = bidrequestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (bidresponseBuilder_ == null) {
          result.bidresponse_ = bidresponse_;
        } else {
          result.bidresponse_ = bidresponseBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.m6r.format.openrtb.MbrBid.JoinedBid) {
          return mergeFrom((eu.m6r.format.openrtb.MbrBid.JoinedBid)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eu.m6r.format.openrtb.MbrBid.JoinedBid other) {
        if (other == eu.m6r.format.openrtb.MbrBid.JoinedBid.getDefaultInstance()) return this;
        if (other.hasBidrequest()) {
          mergeBidrequest(other.getBidrequest());
        }
        if (other.hasBidresponse()) {
          mergeBidresponse(other.getBidresponse());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasBidrequest()) {
          if (!getBidrequest().isInitialized()) {
            
            return false;
          }
        }
        if (hasBidresponse()) {
          if (!getBidresponse().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eu.m6r.format.openrtb.MbrBid.JoinedBid parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eu.m6r.format.openrtb.MbrBid.JoinedBid) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.openrtb.OpenRtb.BidRequest bidrequest_ = com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.google.openrtb.OpenRtb.BidRequest, com.google.openrtb.OpenRtb.BidRequest.Builder, com.google.openrtb.OpenRtb.BidRequestOrBuilder> bidrequestBuilder_;
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public boolean hasBidrequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidRequest getBidrequest() {
        if (bidrequestBuilder_ == null) {
          return bidrequest_;
        } else {
          return bidrequestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public Builder setBidrequest(com.google.openrtb.OpenRtb.BidRequest value) {
        if (bidrequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bidrequest_ = value;
          onChanged();
        } else {
          bidrequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public Builder setBidrequest(
          com.google.openrtb.OpenRtb.BidRequest.Builder builderForValue) {
        if (bidrequestBuilder_ == null) {
          bidrequest_ = builderForValue.build();
          onChanged();
        } else {
          bidrequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public Builder mergeBidrequest(com.google.openrtb.OpenRtb.BidRequest value) {
        if (bidrequestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              bidrequest_ != com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance()) {
            bidrequest_ =
              com.google.openrtb.OpenRtb.BidRequest.newBuilder(bidrequest_).mergeFrom(value).buildPartial();
          } else {
            bidrequest_ = value;
          }
          onChanged();
        } else {
          bidrequestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public Builder clearBidrequest() {
        if (bidrequestBuilder_ == null) {
          bidrequest_ = com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance();
          onChanged();
        } else {
          bidrequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidRequest.Builder getBidrequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBidrequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidRequestOrBuilder getBidrequestOrBuilder() {
        if (bidrequestBuilder_ != null) {
          return bidrequestBuilder_.getMessageOrBuilder();
        } else {
          return bidrequest_;
        }
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.openrtb.OpenRtb.BidRequest, com.google.openrtb.OpenRtb.BidRequest.Builder, com.google.openrtb.OpenRtb.BidRequestOrBuilder> 
          getBidrequestFieldBuilder() {
        if (bidrequestBuilder_ == null) {
          bidrequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.openrtb.OpenRtb.BidRequest, com.google.openrtb.OpenRtb.BidRequest.Builder, com.google.openrtb.OpenRtb.BidRequestOrBuilder>(
                  getBidrequest(),
                  getParentForChildren(),
                  isClean());
          bidrequest_ = null;
        }
        return bidrequestBuilder_;
      }

      private com.google.openrtb.OpenRtb.BidResponse bidresponse_ = com.google.openrtb.OpenRtb.BidResponse.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.google.openrtb.OpenRtb.BidResponse, com.google.openrtb.OpenRtb.BidResponse.Builder, com.google.openrtb.OpenRtb.BidResponseOrBuilder> bidresponseBuilder_;
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public boolean hasBidresponse() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidResponse getBidresponse() {
        if (bidresponseBuilder_ == null) {
          return bidresponse_;
        } else {
          return bidresponseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public Builder setBidresponse(com.google.openrtb.OpenRtb.BidResponse value) {
        if (bidresponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bidresponse_ = value;
          onChanged();
        } else {
          bidresponseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public Builder setBidresponse(
          com.google.openrtb.OpenRtb.BidResponse.Builder builderForValue) {
        if (bidresponseBuilder_ == null) {
          bidresponse_ = builderForValue.build();
          onChanged();
        } else {
          bidresponseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public Builder mergeBidresponse(com.google.openrtb.OpenRtb.BidResponse value) {
        if (bidresponseBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              bidresponse_ != com.google.openrtb.OpenRtb.BidResponse.getDefaultInstance()) {
            bidresponse_ =
              com.google.openrtb.OpenRtb.BidResponse.newBuilder(bidresponse_).mergeFrom(value).buildPartial();
          } else {
            bidresponse_ = value;
          }
          onChanged();
        } else {
          bidresponseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public Builder clearBidresponse() {
        if (bidresponseBuilder_ == null) {
          bidresponse_ = com.google.openrtb.OpenRtb.BidResponse.getDefaultInstance();
          onChanged();
        } else {
          bidresponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidResponse.Builder getBidresponseBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getBidresponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidResponseOrBuilder getBidresponseOrBuilder() {
        if (bidresponseBuilder_ != null) {
          return bidresponseBuilder_.getMessageOrBuilder();
        } else {
          return bidresponse_;
        }
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.openrtb.OpenRtb.BidResponse, com.google.openrtb.OpenRtb.BidResponse.Builder, com.google.openrtb.OpenRtb.BidResponseOrBuilder> 
          getBidresponseFieldBuilder() {
        if (bidresponseBuilder_ == null) {
          bidresponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.openrtb.OpenRtb.BidResponse, com.google.openrtb.OpenRtb.BidResponse.Builder, com.google.openrtb.OpenRtb.BidResponseOrBuilder>(
                  getBidresponse(),
                  getParentForChildren(),
                  isClean());
          bidresponse_ = null;
        }
        return bidresponseBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:eu.m6r.format.openrtb.JoinedBid)
    }

    static {
      defaultInstance = new JoinedBid(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:eu.m6r.format.openrtb.JoinedBid)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_m6r_format_openrtb_JoinedBid_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_m6r_format_openrtb_JoinedBid_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmbr-bid.proto\022\025eu.m6r.format.openrtb\032\r" +
      "openrtb.proto\"u\n\tJoinedBid\0222\n\nbidrequest" +
      "\030\001 \001(\0132\036.com.google.openrtb.BidRequest\0224" +
      "\n\013bidresponse\030\002 \001(\0132\037.com.google.openrtb" +
      ".BidResponse"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.openrtb.OpenRtb.getDescriptor(),
        }, assigner);
    internal_static_eu_m6r_format_openrtb_JoinedBid_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eu_m6r_format_openrtb_JoinedBid_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eu_m6r_format_openrtb_JoinedBid_descriptor,
        new java.lang.String[] { "Bidrequest", "Bidresponse", });
    com.google.openrtb.OpenRtb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
