// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mbr-click.proto

package eu.m6r.format.openrtb;

public final class MbrClick {
  private MbrClick() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ClickOrBuilder extends
      // @@protoc_insertion_point(interface_extends:eu.m6r.format.openrtb.Click)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
     *
     * <pre>
     * Mbr: Contains all data regarding the request.
     * </pre>
     */
    boolean hasRequest();
    /**
     * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
     *
     * <pre>
     * Mbr: Contains all data regarding the request.
     * </pre>
     */
    com.google.openrtb.OpenRtb.BidRequest getRequest();
    /**
     * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
     *
     * <pre>
     * Mbr: Contains all data regarding the request.
     * </pre>
     */
    com.google.openrtb.OpenRtb.BidRequestOrBuilder getRequestOrBuilder();

    /**
     * <code>optional string impressionid = 2;</code>
     *
     * <pre>
     * Mbr: The id of the corresponding Impression object.
     * </pre>
     */
    boolean hasImpressionid();
    /**
     * <code>optional string impressionid = 2;</code>
     *
     * <pre>
     * Mbr: The id of the corresponding Impression object.
     * </pre>
     */
    java.lang.String getImpressionid();
    /**
     * <code>optional string impressionid = 2;</code>
     *
     * <pre>
     * Mbr: The id of the corresponding Impression object.
     * </pre>
     */
    com.google.protobuf.ByteString
        getImpressionidBytes();

    /**
     * <code>optional .eu.m6r.format.openrtb.Amount revenue = 3;</code>
     *
     * <pre>
     * Mbr: Amount earned for this impression.
     * </pre>
     */
    boolean hasRevenue();
    /**
     * <code>optional .eu.m6r.format.openrtb.Amount revenue = 3;</code>
     *
     * <pre>
     * Mbr: Amount earned for this impression.
     * </pre>
     */
    org.adscale.format.opertb.AmountMessage.Amount getRevenue();
    /**
     * <code>optional .eu.m6r.format.openrtb.Amount revenue = 3;</code>
     *
     * <pre>
     * Mbr: Amount earned for this impression.
     * </pre>
     */
    org.adscale.format.opertb.AmountMessage.AmountOrBuilder getRevenueOrBuilder();
  }
  /**
   * Protobuf type {@code eu.m6r.format.openrtb.Click}
   *
   * <pre>
   * Mbr: Click specific values and request.
   * </pre>
   */
  public static final class Click extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:eu.m6r.format.openrtb.Click)
      ClickOrBuilder {
    // Use Click.newBuilder() to construct.
    private Click(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Click(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Click defaultInstance;
    public static Click getDefaultInstance() {
      return defaultInstance;
    }

    public Click getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Click(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.openrtb.OpenRtb.BidRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(com.google.openrtb.OpenRtb.BidRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              impressionid_ = bs;
              break;
            }
            case 26: {
              org.adscale.format.opertb.AmountMessage.Amount.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = revenue_.toBuilder();
              }
              revenue_ = input.readMessage(org.adscale.format.opertb.AmountMessage.Amount.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(revenue_);
                revenue_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.m6r.format.openrtb.MbrClick.internal_static_eu_m6r_format_openrtb_Click_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.m6r.format.openrtb.MbrClick.internal_static_eu_m6r_format_openrtb_Click_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.m6r.format.openrtb.MbrClick.Click.class, eu.m6r.format.openrtb.MbrClick.Click.Builder.class);
    }

    public static com.google.protobuf.Parser<Click> PARSER =
        new com.google.protobuf.AbstractParser<Click>() {
      public Click parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Click(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Click> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int REQUEST_FIELD_NUMBER = 1;
    private com.google.openrtb.OpenRtb.BidRequest request_;
    /**
     * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
     *
     * <pre>
     * Mbr: Contains all data regarding the request.
     * </pre>
     */
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
     *
     * <pre>
     * Mbr: Contains all data regarding the request.
     * </pre>
     */
    public com.google.openrtb.OpenRtb.BidRequest getRequest() {
      return request_;
    }
    /**
     * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
     *
     * <pre>
     * Mbr: Contains all data regarding the request.
     * </pre>
     */
    public com.google.openrtb.OpenRtb.BidRequestOrBuilder getRequestOrBuilder() {
      return request_;
    }

    public static final int IMPRESSIONID_FIELD_NUMBER = 2;
    private java.lang.Object impressionid_;
    /**
     * <code>optional string impressionid = 2;</code>
     *
     * <pre>
     * Mbr: The id of the corresponding Impression object.
     * </pre>
     */
    public boolean hasImpressionid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string impressionid = 2;</code>
     *
     * <pre>
     * Mbr: The id of the corresponding Impression object.
     * </pre>
     */
    public java.lang.String getImpressionid() {
      java.lang.Object ref = impressionid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          impressionid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string impressionid = 2;</code>
     *
     * <pre>
     * Mbr: The id of the corresponding Impression object.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getImpressionidBytes() {
      java.lang.Object ref = impressionid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        impressionid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REVENUE_FIELD_NUMBER = 3;
    private org.adscale.format.opertb.AmountMessage.Amount revenue_;
    /**
     * <code>optional .eu.m6r.format.openrtb.Amount revenue = 3;</code>
     *
     * <pre>
     * Mbr: Amount earned for this impression.
     * </pre>
     */
    public boolean hasRevenue() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .eu.m6r.format.openrtb.Amount revenue = 3;</code>
     *
     * <pre>
     * Mbr: Amount earned for this impression.
     * </pre>
     */
    public org.adscale.format.opertb.AmountMessage.Amount getRevenue() {
      return revenue_;
    }
    /**
     * <code>optional .eu.m6r.format.openrtb.Amount revenue = 3;</code>
     *
     * <pre>
     * Mbr: Amount earned for this impression.
     * </pre>
     */
    public org.adscale.format.opertb.AmountMessage.AmountOrBuilder getRevenueOrBuilder() {
      return revenue_;
    }

    private void initFields() {
      request_ = com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance();
      impressionid_ = "";
      revenue_ = org.adscale.format.opertb.AmountMessage.Amount.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasRequest()) {
        if (!getRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, request_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getImpressionidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, revenue_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, request_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getImpressionidBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, revenue_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static eu.m6r.format.openrtb.MbrClick.Click parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.m6r.format.openrtb.MbrClick.Click parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.m6r.format.openrtb.MbrClick.Click parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.m6r.format.openrtb.MbrClick.Click parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.m6r.format.openrtb.MbrClick.Click parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.m6r.format.openrtb.MbrClick.Click parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static eu.m6r.format.openrtb.MbrClick.Click parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static eu.m6r.format.openrtb.MbrClick.Click parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static eu.m6r.format.openrtb.MbrClick.Click parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.m6r.format.openrtb.MbrClick.Click parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.m6r.format.openrtb.MbrClick.Click prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eu.m6r.format.openrtb.Click}
     *
     * <pre>
     * Mbr: Click specific values and request.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:eu.m6r.format.openrtb.Click)
        eu.m6r.format.openrtb.MbrClick.ClickOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.m6r.format.openrtb.MbrClick.internal_static_eu_m6r_format_openrtb_Click_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.m6r.format.openrtb.MbrClick.internal_static_eu_m6r_format_openrtb_Click_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eu.m6r.format.openrtb.MbrClick.Click.class, eu.m6r.format.openrtb.MbrClick.Click.Builder.class);
      }

      // Construct using eu.m6r.format.openrtb.MbrClick.Click.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRequestFieldBuilder();
          getRevenueFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        impressionid_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (revenueBuilder_ == null) {
          revenue_ = org.adscale.format.opertb.AmountMessage.Amount.getDefaultInstance();
        } else {
          revenueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.m6r.format.openrtb.MbrClick.internal_static_eu_m6r_format_openrtb_Click_descriptor;
      }

      public eu.m6r.format.openrtb.MbrClick.Click getDefaultInstanceForType() {
        return eu.m6r.format.openrtb.MbrClick.Click.getDefaultInstance();
      }

      public eu.m6r.format.openrtb.MbrClick.Click build() {
        eu.m6r.format.openrtb.MbrClick.Click result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public eu.m6r.format.openrtb.MbrClick.Click buildPartial() {
        eu.m6r.format.openrtb.MbrClick.Click result = new eu.m6r.format.openrtb.MbrClick.Click(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.impressionid_ = impressionid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (revenueBuilder_ == null) {
          result.revenue_ = revenue_;
        } else {
          result.revenue_ = revenueBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.m6r.format.openrtb.MbrClick.Click) {
          return mergeFrom((eu.m6r.format.openrtb.MbrClick.Click)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eu.m6r.format.openrtb.MbrClick.Click other) {
        if (other == eu.m6r.format.openrtb.MbrClick.Click.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.hasImpressionid()) {
          bitField0_ |= 0x00000002;
          impressionid_ = other.impressionid_;
          onChanged();
        }
        if (other.hasRevenue()) {
          mergeRevenue(other.getRevenue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasRequest()) {
          if (!getRequest().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eu.m6r.format.openrtb.MbrClick.Click parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eu.m6r.format.openrtb.MbrClick.Click) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.openrtb.OpenRtb.BidRequest request_ = com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.google.openrtb.OpenRtb.BidRequest, com.google.openrtb.OpenRtb.BidRequest.Builder, com.google.openrtb.OpenRtb.BidRequestOrBuilder> requestBuilder_;
      /**
       * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
       *
       * <pre>
       * Mbr: Contains all data regarding the request.
       * </pre>
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
       *
       * <pre>
       * Mbr: Contains all data regarding the request.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidRequest getRequest() {
        if (requestBuilder_ == null) {
          return request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
       *
       * <pre>
       * Mbr: Contains all data regarding the request.
       * </pre>
       */
      public Builder setRequest(com.google.openrtb.OpenRtb.BidRequest value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
       *
       * <pre>
       * Mbr: Contains all data regarding the request.
       * </pre>
       */
      public Builder setRequest(
          com.google.openrtb.OpenRtb.BidRequest.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
       *
       * <pre>
       * Mbr: Contains all data regarding the request.
       * </pre>
       */
      public Builder mergeRequest(com.google.openrtb.OpenRtb.BidRequest value) {
        if (requestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              request_ != com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance()) {
            request_ =
              com.google.openrtb.OpenRtb.BidRequest.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
       *
       * <pre>
       * Mbr: Contains all data regarding the request.
       * </pre>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance();
          onChanged();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
       *
       * <pre>
       * Mbr: Contains all data regarding the request.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidRequest.Builder getRequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
       *
       * <pre>
       * Mbr: Contains all data regarding the request.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidRequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_;
        }
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
       *
       * <pre>
       * Mbr: Contains all data regarding the request.
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.openrtb.OpenRtb.BidRequest, com.google.openrtb.OpenRtb.BidRequest.Builder, com.google.openrtb.OpenRtb.BidRequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.openrtb.OpenRtb.BidRequest, com.google.openrtb.OpenRtb.BidRequest.Builder, com.google.openrtb.OpenRtb.BidRequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private java.lang.Object impressionid_ = "";
      /**
       * <code>optional string impressionid = 2;</code>
       *
       * <pre>
       * Mbr: The id of the corresponding Impression object.
       * </pre>
       */
      public boolean hasImpressionid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string impressionid = 2;</code>
       *
       * <pre>
       * Mbr: The id of the corresponding Impression object.
       * </pre>
       */
      public java.lang.String getImpressionid() {
        java.lang.Object ref = impressionid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            impressionid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string impressionid = 2;</code>
       *
       * <pre>
       * Mbr: The id of the corresponding Impression object.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getImpressionidBytes() {
        java.lang.Object ref = impressionid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          impressionid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string impressionid = 2;</code>
       *
       * <pre>
       * Mbr: The id of the corresponding Impression object.
       * </pre>
       */
      public Builder setImpressionid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        impressionid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string impressionid = 2;</code>
       *
       * <pre>
       * Mbr: The id of the corresponding Impression object.
       * </pre>
       */
      public Builder clearImpressionid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        impressionid_ = getDefaultInstance().getImpressionid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string impressionid = 2;</code>
       *
       * <pre>
       * Mbr: The id of the corresponding Impression object.
       * </pre>
       */
      public Builder setImpressionidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        impressionid_ = value;
        onChanged();
        return this;
      }

      private org.adscale.format.opertb.AmountMessage.Amount revenue_ = org.adscale.format.opertb.AmountMessage.Amount.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.adscale.format.opertb.AmountMessage.Amount, org.adscale.format.opertb.AmountMessage.Amount.Builder, org.adscale.format.opertb.AmountMessage.AmountOrBuilder> revenueBuilder_;
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount revenue = 3;</code>
       *
       * <pre>
       * Mbr: Amount earned for this impression.
       * </pre>
       */
      public boolean hasRevenue() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount revenue = 3;</code>
       *
       * <pre>
       * Mbr: Amount earned for this impression.
       * </pre>
       */
      public org.adscale.format.opertb.AmountMessage.Amount getRevenue() {
        if (revenueBuilder_ == null) {
          return revenue_;
        } else {
          return revenueBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount revenue = 3;</code>
       *
       * <pre>
       * Mbr: Amount earned for this impression.
       * </pre>
       */
      public Builder setRevenue(org.adscale.format.opertb.AmountMessage.Amount value) {
        if (revenueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          revenue_ = value;
          onChanged();
        } else {
          revenueBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount revenue = 3;</code>
       *
       * <pre>
       * Mbr: Amount earned for this impression.
       * </pre>
       */
      public Builder setRevenue(
          org.adscale.format.opertb.AmountMessage.Amount.Builder builderForValue) {
        if (revenueBuilder_ == null) {
          revenue_ = builderForValue.build();
          onChanged();
        } else {
          revenueBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount revenue = 3;</code>
       *
       * <pre>
       * Mbr: Amount earned for this impression.
       * </pre>
       */
      public Builder mergeRevenue(org.adscale.format.opertb.AmountMessage.Amount value) {
        if (revenueBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              revenue_ != org.adscale.format.opertb.AmountMessage.Amount.getDefaultInstance()) {
            revenue_ =
              org.adscale.format.opertb.AmountMessage.Amount.newBuilder(revenue_).mergeFrom(value).buildPartial();
          } else {
            revenue_ = value;
          }
          onChanged();
        } else {
          revenueBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount revenue = 3;</code>
       *
       * <pre>
       * Mbr: Amount earned for this impression.
       * </pre>
       */
      public Builder clearRevenue() {
        if (revenueBuilder_ == null) {
          revenue_ = org.adscale.format.opertb.AmountMessage.Amount.getDefaultInstance();
          onChanged();
        } else {
          revenueBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount revenue = 3;</code>
       *
       * <pre>
       * Mbr: Amount earned for this impression.
       * </pre>
       */
      public org.adscale.format.opertb.AmountMessage.Amount.Builder getRevenueBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getRevenueFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount revenue = 3;</code>
       *
       * <pre>
       * Mbr: Amount earned for this impression.
       * </pre>
       */
      public org.adscale.format.opertb.AmountMessage.AmountOrBuilder getRevenueOrBuilder() {
        if (revenueBuilder_ != null) {
          return revenueBuilder_.getMessageOrBuilder();
        } else {
          return revenue_;
        }
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount revenue = 3;</code>
       *
       * <pre>
       * Mbr: Amount earned for this impression.
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.adscale.format.opertb.AmountMessage.Amount, org.adscale.format.opertb.AmountMessage.Amount.Builder, org.adscale.format.opertb.AmountMessage.AmountOrBuilder> 
          getRevenueFieldBuilder() {
        if (revenueBuilder_ == null) {
          revenueBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.adscale.format.opertb.AmountMessage.Amount, org.adscale.format.opertb.AmountMessage.Amount.Builder, org.adscale.format.opertb.AmountMessage.AmountOrBuilder>(
                  getRevenue(),
                  getParentForChildren(),
                  isClean());
          revenue_ = null;
        }
        return revenueBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:eu.m6r.format.openrtb.Click)
    }

    static {
      defaultInstance = new Click(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:eu.m6r.format.openrtb.Click)
  }

  public interface JoinedClickOrBuilder extends
      // @@protoc_insertion_point(interface_extends:eu.m6r.format.openrtb.JoinedClick)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
     *
     * <pre>
     * Mbr: mbr-bid-request.proto.
     * </pre>
     */
    boolean hasBidrequest();
    /**
     * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
     *
     * <pre>
     * Mbr: mbr-bid-request.proto.
     * </pre>
     */
    com.google.openrtb.OpenRtb.BidRequest getBidrequest();
    /**
     * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
     *
     * <pre>
     * Mbr: mbr-bid-request.proto.
     * </pre>
     */
    com.google.openrtb.OpenRtb.BidRequestOrBuilder getBidrequestOrBuilder();

    /**
     * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
     *
     * <pre>
     * Mbr: mbr-bid-response.proto.
     * </pre>
     */
    boolean hasBidresponse();
    /**
     * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
     *
     * <pre>
     * Mbr: mbr-bid-response.proto.
     * </pre>
     */
    com.google.openrtb.OpenRtb.BidResponse getBidresponse();
    /**
     * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
     *
     * <pre>
     * Mbr: mbr-bid-response.proto.
     * </pre>
     */
    com.google.openrtb.OpenRtb.BidResponseOrBuilder getBidresponseOrBuilder();

    /**
     * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
     *
     * <pre>
     * Mbr: mbr-win.proto.
     * </pre>
     */
    boolean hasWin();
    /**
     * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
     *
     * <pre>
     * Mbr: mbr-win.proto.
     * </pre>
     */
    eu.m6r.format.openrtb.MbrWin.Win getWin();
    /**
     * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
     *
     * <pre>
     * Mbr: mbr-win.proto.
     * </pre>
     */
    eu.m6r.format.openrtb.MbrWin.WinOrBuilder getWinOrBuilder();

    /**
     * <code>optional .eu.m6r.format.openrtb.Impression impression = 4;</code>
     *
     * <pre>
     * Mbr: mbr-impression.proto.
     * </pre>
     */
    boolean hasImpression();
    /**
     * <code>optional .eu.m6r.format.openrtb.Impression impression = 4;</code>
     *
     * <pre>
     * Mbr: mbr-impression.proto.
     * </pre>
     */
    eu.m6r.format.openrtb.MbrImpression.Impression getImpression();
    /**
     * <code>optional .eu.m6r.format.openrtb.Impression impression = 4;</code>
     *
     * <pre>
     * Mbr: mbr-impression.proto.
     * </pre>
     */
    eu.m6r.format.openrtb.MbrImpression.ImpressionOrBuilder getImpressionOrBuilder();

    /**
     * <code>optional .eu.m6r.format.openrtb.Click click = 5;</code>
     *
     * <pre>
     * Mbr: mbr-click.proto.
     * </pre>
     */
    boolean hasClick();
    /**
     * <code>optional .eu.m6r.format.openrtb.Click click = 5;</code>
     *
     * <pre>
     * Mbr: mbr-click.proto.
     * </pre>
     */
    eu.m6r.format.openrtb.MbrClick.Click getClick();
    /**
     * <code>optional .eu.m6r.format.openrtb.Click click = 5;</code>
     *
     * <pre>
     * Mbr: mbr-click.proto.
     * </pre>
     */
    eu.m6r.format.openrtb.MbrClick.ClickOrBuilder getClickOrBuilder();
  }
  /**
   * Protobuf type {@code eu.m6r.format.openrtb.JoinedClick}
   *
   * <pre>
   * Mbr: The event history of a click.
   * </pre>
   */
  public static final class JoinedClick extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:eu.m6r.format.openrtb.JoinedClick)
      JoinedClickOrBuilder {
    // Use JoinedClick.newBuilder() to construct.
    private JoinedClick(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private JoinedClick(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final JoinedClick defaultInstance;
    public static JoinedClick getDefaultInstance() {
      return defaultInstance;
    }

    public JoinedClick getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private JoinedClick(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.openrtb.OpenRtb.BidRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = bidrequest_.toBuilder();
              }
              bidrequest_ = input.readMessage(com.google.openrtb.OpenRtb.BidRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bidrequest_);
                bidrequest_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.google.openrtb.OpenRtb.BidResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = bidresponse_.toBuilder();
              }
              bidresponse_ = input.readMessage(com.google.openrtb.OpenRtb.BidResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bidresponse_);
                bidresponse_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              eu.m6r.format.openrtb.MbrWin.Win.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = win_.toBuilder();
              }
              win_ = input.readMessage(eu.m6r.format.openrtb.MbrWin.Win.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(win_);
                win_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              eu.m6r.format.openrtb.MbrImpression.Impression.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = impression_.toBuilder();
              }
              impression_ = input.readMessage(eu.m6r.format.openrtb.MbrImpression.Impression.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(impression_);
                impression_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 42: {
              eu.m6r.format.openrtb.MbrClick.Click.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = click_.toBuilder();
              }
              click_ = input.readMessage(eu.m6r.format.openrtb.MbrClick.Click.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(click_);
                click_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.m6r.format.openrtb.MbrClick.internal_static_eu_m6r_format_openrtb_JoinedClick_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.m6r.format.openrtb.MbrClick.internal_static_eu_m6r_format_openrtb_JoinedClick_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.m6r.format.openrtb.MbrClick.JoinedClick.class, eu.m6r.format.openrtb.MbrClick.JoinedClick.Builder.class);
    }

    public static com.google.protobuf.Parser<JoinedClick> PARSER =
        new com.google.protobuf.AbstractParser<JoinedClick>() {
      public JoinedClick parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JoinedClick(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<JoinedClick> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BIDREQUEST_FIELD_NUMBER = 1;
    private com.google.openrtb.OpenRtb.BidRequest bidrequest_;
    /**
     * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
     *
     * <pre>
     * Mbr: mbr-bid-request.proto.
     * </pre>
     */
    public boolean hasBidrequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
     *
     * <pre>
     * Mbr: mbr-bid-request.proto.
     * </pre>
     */
    public com.google.openrtb.OpenRtb.BidRequest getBidrequest() {
      return bidrequest_;
    }
    /**
     * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
     *
     * <pre>
     * Mbr: mbr-bid-request.proto.
     * </pre>
     */
    public com.google.openrtb.OpenRtb.BidRequestOrBuilder getBidrequestOrBuilder() {
      return bidrequest_;
    }

    public static final int BIDRESPONSE_FIELD_NUMBER = 2;
    private com.google.openrtb.OpenRtb.BidResponse bidresponse_;
    /**
     * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
     *
     * <pre>
     * Mbr: mbr-bid-response.proto.
     * </pre>
     */
    public boolean hasBidresponse() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
     *
     * <pre>
     * Mbr: mbr-bid-response.proto.
     * </pre>
     */
    public com.google.openrtb.OpenRtb.BidResponse getBidresponse() {
      return bidresponse_;
    }
    /**
     * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
     *
     * <pre>
     * Mbr: mbr-bid-response.proto.
     * </pre>
     */
    public com.google.openrtb.OpenRtb.BidResponseOrBuilder getBidresponseOrBuilder() {
      return bidresponse_;
    }

    public static final int WIN_FIELD_NUMBER = 3;
    private eu.m6r.format.openrtb.MbrWin.Win win_;
    /**
     * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
     *
     * <pre>
     * Mbr: mbr-win.proto.
     * </pre>
     */
    public boolean hasWin() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
     *
     * <pre>
     * Mbr: mbr-win.proto.
     * </pre>
     */
    public eu.m6r.format.openrtb.MbrWin.Win getWin() {
      return win_;
    }
    /**
     * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
     *
     * <pre>
     * Mbr: mbr-win.proto.
     * </pre>
     */
    public eu.m6r.format.openrtb.MbrWin.WinOrBuilder getWinOrBuilder() {
      return win_;
    }

    public static final int IMPRESSION_FIELD_NUMBER = 4;
    private eu.m6r.format.openrtb.MbrImpression.Impression impression_;
    /**
     * <code>optional .eu.m6r.format.openrtb.Impression impression = 4;</code>
     *
     * <pre>
     * Mbr: mbr-impression.proto.
     * </pre>
     */
    public boolean hasImpression() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .eu.m6r.format.openrtb.Impression impression = 4;</code>
     *
     * <pre>
     * Mbr: mbr-impression.proto.
     * </pre>
     */
    public eu.m6r.format.openrtb.MbrImpression.Impression getImpression() {
      return impression_;
    }
    /**
     * <code>optional .eu.m6r.format.openrtb.Impression impression = 4;</code>
     *
     * <pre>
     * Mbr: mbr-impression.proto.
     * </pre>
     */
    public eu.m6r.format.openrtb.MbrImpression.ImpressionOrBuilder getImpressionOrBuilder() {
      return impression_;
    }

    public static final int CLICK_FIELD_NUMBER = 5;
    private eu.m6r.format.openrtb.MbrClick.Click click_;
    /**
     * <code>optional .eu.m6r.format.openrtb.Click click = 5;</code>
     *
     * <pre>
     * Mbr: mbr-click.proto.
     * </pre>
     */
    public boolean hasClick() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional .eu.m6r.format.openrtb.Click click = 5;</code>
     *
     * <pre>
     * Mbr: mbr-click.proto.
     * </pre>
     */
    public eu.m6r.format.openrtb.MbrClick.Click getClick() {
      return click_;
    }
    /**
     * <code>optional .eu.m6r.format.openrtb.Click click = 5;</code>
     *
     * <pre>
     * Mbr: mbr-click.proto.
     * </pre>
     */
    public eu.m6r.format.openrtb.MbrClick.ClickOrBuilder getClickOrBuilder() {
      return click_;
    }

    private void initFields() {
      bidrequest_ = com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance();
      bidresponse_ = com.google.openrtb.OpenRtb.BidResponse.getDefaultInstance();
      win_ = eu.m6r.format.openrtb.MbrWin.Win.getDefaultInstance();
      impression_ = eu.m6r.format.openrtb.MbrImpression.Impression.getDefaultInstance();
      click_ = eu.m6r.format.openrtb.MbrClick.Click.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasBidrequest()) {
        if (!getBidrequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasBidresponse()) {
        if (!getBidresponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasWin()) {
        if (!getWin().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasImpression()) {
        if (!getImpression().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasClick()) {
        if (!getClick().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, bidrequest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, bidresponse_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, win_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, impression_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, click_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, bidrequest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, bidresponse_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, win_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, impression_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, click_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static eu.m6r.format.openrtb.MbrClick.JoinedClick parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.m6r.format.openrtb.MbrClick.JoinedClick parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.m6r.format.openrtb.MbrClick.JoinedClick parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.m6r.format.openrtb.MbrClick.JoinedClick parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.m6r.format.openrtb.MbrClick.JoinedClick parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.m6r.format.openrtb.MbrClick.JoinedClick parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static eu.m6r.format.openrtb.MbrClick.JoinedClick parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static eu.m6r.format.openrtb.MbrClick.JoinedClick parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static eu.m6r.format.openrtb.MbrClick.JoinedClick parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.m6r.format.openrtb.MbrClick.JoinedClick parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.m6r.format.openrtb.MbrClick.JoinedClick prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eu.m6r.format.openrtb.JoinedClick}
     *
     * <pre>
     * Mbr: The event history of a click.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:eu.m6r.format.openrtb.JoinedClick)
        eu.m6r.format.openrtb.MbrClick.JoinedClickOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.m6r.format.openrtb.MbrClick.internal_static_eu_m6r_format_openrtb_JoinedClick_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.m6r.format.openrtb.MbrClick.internal_static_eu_m6r_format_openrtb_JoinedClick_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eu.m6r.format.openrtb.MbrClick.JoinedClick.class, eu.m6r.format.openrtb.MbrClick.JoinedClick.Builder.class);
      }

      // Construct using eu.m6r.format.openrtb.MbrClick.JoinedClick.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBidrequestFieldBuilder();
          getBidresponseFieldBuilder();
          getWinFieldBuilder();
          getImpressionFieldBuilder();
          getClickFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (bidrequestBuilder_ == null) {
          bidrequest_ = com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance();
        } else {
          bidrequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (bidresponseBuilder_ == null) {
          bidresponse_ = com.google.openrtb.OpenRtb.BidResponse.getDefaultInstance();
        } else {
          bidresponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (winBuilder_ == null) {
          win_ = eu.m6r.format.openrtb.MbrWin.Win.getDefaultInstance();
        } else {
          winBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (impressionBuilder_ == null) {
          impression_ = eu.m6r.format.openrtb.MbrImpression.Impression.getDefaultInstance();
        } else {
          impressionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (clickBuilder_ == null) {
          click_ = eu.m6r.format.openrtb.MbrClick.Click.getDefaultInstance();
        } else {
          clickBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.m6r.format.openrtb.MbrClick.internal_static_eu_m6r_format_openrtb_JoinedClick_descriptor;
      }

      public eu.m6r.format.openrtb.MbrClick.JoinedClick getDefaultInstanceForType() {
        return eu.m6r.format.openrtb.MbrClick.JoinedClick.getDefaultInstance();
      }

      public eu.m6r.format.openrtb.MbrClick.JoinedClick build() {
        eu.m6r.format.openrtb.MbrClick.JoinedClick result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public eu.m6r.format.openrtb.MbrClick.JoinedClick buildPartial() {
        eu.m6r.format.openrtb.MbrClick.JoinedClick result = new eu.m6r.format.openrtb.MbrClick.JoinedClick(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (bidrequestBuilder_ == null) {
          result.bidrequest_ = bidrequest_;
        } else {
          result.bidrequest_ = bidrequestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (bidresponseBuilder_ == null) {
          result.bidresponse_ = bidresponse_;
        } else {
          result.bidresponse_ = bidresponseBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (winBuilder_ == null) {
          result.win_ = win_;
        } else {
          result.win_ = winBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (impressionBuilder_ == null) {
          result.impression_ = impression_;
        } else {
          result.impression_ = impressionBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (clickBuilder_ == null) {
          result.click_ = click_;
        } else {
          result.click_ = clickBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.m6r.format.openrtb.MbrClick.JoinedClick) {
          return mergeFrom((eu.m6r.format.openrtb.MbrClick.JoinedClick)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eu.m6r.format.openrtb.MbrClick.JoinedClick other) {
        if (other == eu.m6r.format.openrtb.MbrClick.JoinedClick.getDefaultInstance()) return this;
        if (other.hasBidrequest()) {
          mergeBidrequest(other.getBidrequest());
        }
        if (other.hasBidresponse()) {
          mergeBidresponse(other.getBidresponse());
        }
        if (other.hasWin()) {
          mergeWin(other.getWin());
        }
        if (other.hasImpression()) {
          mergeImpression(other.getImpression());
        }
        if (other.hasClick()) {
          mergeClick(other.getClick());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasBidrequest()) {
          if (!getBidrequest().isInitialized()) {
            
            return false;
          }
        }
        if (hasBidresponse()) {
          if (!getBidresponse().isInitialized()) {
            
            return false;
          }
        }
        if (hasWin()) {
          if (!getWin().isInitialized()) {
            
            return false;
          }
        }
        if (hasImpression()) {
          if (!getImpression().isInitialized()) {
            
            return false;
          }
        }
        if (hasClick()) {
          if (!getClick().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eu.m6r.format.openrtb.MbrClick.JoinedClick parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eu.m6r.format.openrtb.MbrClick.JoinedClick) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.openrtb.OpenRtb.BidRequest bidrequest_ = com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.google.openrtb.OpenRtb.BidRequest, com.google.openrtb.OpenRtb.BidRequest.Builder, com.google.openrtb.OpenRtb.BidRequestOrBuilder> bidrequestBuilder_;
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public boolean hasBidrequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidRequest getBidrequest() {
        if (bidrequestBuilder_ == null) {
          return bidrequest_;
        } else {
          return bidrequestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public Builder setBidrequest(com.google.openrtb.OpenRtb.BidRequest value) {
        if (bidrequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bidrequest_ = value;
          onChanged();
        } else {
          bidrequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public Builder setBidrequest(
          com.google.openrtb.OpenRtb.BidRequest.Builder builderForValue) {
        if (bidrequestBuilder_ == null) {
          bidrequest_ = builderForValue.build();
          onChanged();
        } else {
          bidrequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public Builder mergeBidrequest(com.google.openrtb.OpenRtb.BidRequest value) {
        if (bidrequestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              bidrequest_ != com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance()) {
            bidrequest_ =
              com.google.openrtb.OpenRtb.BidRequest.newBuilder(bidrequest_).mergeFrom(value).buildPartial();
          } else {
            bidrequest_ = value;
          }
          onChanged();
        } else {
          bidrequestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public Builder clearBidrequest() {
        if (bidrequestBuilder_ == null) {
          bidrequest_ = com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance();
          onChanged();
        } else {
          bidrequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidRequest.Builder getBidrequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBidrequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidRequestOrBuilder getBidrequestOrBuilder() {
        if (bidrequestBuilder_ != null) {
          return bidrequestBuilder_.getMessageOrBuilder();
        } else {
          return bidrequest_;
        }
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.openrtb.OpenRtb.BidRequest, com.google.openrtb.OpenRtb.BidRequest.Builder, com.google.openrtb.OpenRtb.BidRequestOrBuilder> 
          getBidrequestFieldBuilder() {
        if (bidrequestBuilder_ == null) {
          bidrequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.openrtb.OpenRtb.BidRequest, com.google.openrtb.OpenRtb.BidRequest.Builder, com.google.openrtb.OpenRtb.BidRequestOrBuilder>(
                  getBidrequest(),
                  getParentForChildren(),
                  isClean());
          bidrequest_ = null;
        }
        return bidrequestBuilder_;
      }

      private com.google.openrtb.OpenRtb.BidResponse bidresponse_ = com.google.openrtb.OpenRtb.BidResponse.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.google.openrtb.OpenRtb.BidResponse, com.google.openrtb.OpenRtb.BidResponse.Builder, com.google.openrtb.OpenRtb.BidResponseOrBuilder> bidresponseBuilder_;
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public boolean hasBidresponse() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidResponse getBidresponse() {
        if (bidresponseBuilder_ == null) {
          return bidresponse_;
        } else {
          return bidresponseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public Builder setBidresponse(com.google.openrtb.OpenRtb.BidResponse value) {
        if (bidresponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bidresponse_ = value;
          onChanged();
        } else {
          bidresponseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public Builder setBidresponse(
          com.google.openrtb.OpenRtb.BidResponse.Builder builderForValue) {
        if (bidresponseBuilder_ == null) {
          bidresponse_ = builderForValue.build();
          onChanged();
        } else {
          bidresponseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public Builder mergeBidresponse(com.google.openrtb.OpenRtb.BidResponse value) {
        if (bidresponseBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              bidresponse_ != com.google.openrtb.OpenRtb.BidResponse.getDefaultInstance()) {
            bidresponse_ =
              com.google.openrtb.OpenRtb.BidResponse.newBuilder(bidresponse_).mergeFrom(value).buildPartial();
          } else {
            bidresponse_ = value;
          }
          onChanged();
        } else {
          bidresponseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public Builder clearBidresponse() {
        if (bidresponseBuilder_ == null) {
          bidresponse_ = com.google.openrtb.OpenRtb.BidResponse.getDefaultInstance();
          onChanged();
        } else {
          bidresponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidResponse.Builder getBidresponseBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getBidresponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidResponseOrBuilder getBidresponseOrBuilder() {
        if (bidresponseBuilder_ != null) {
          return bidresponseBuilder_.getMessageOrBuilder();
        } else {
          return bidresponse_;
        }
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.openrtb.OpenRtb.BidResponse, com.google.openrtb.OpenRtb.BidResponse.Builder, com.google.openrtb.OpenRtb.BidResponseOrBuilder> 
          getBidresponseFieldBuilder() {
        if (bidresponseBuilder_ == null) {
          bidresponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.openrtb.OpenRtb.BidResponse, com.google.openrtb.OpenRtb.BidResponse.Builder, com.google.openrtb.OpenRtb.BidResponseOrBuilder>(
                  getBidresponse(),
                  getParentForChildren(),
                  isClean());
          bidresponse_ = null;
        }
        return bidresponseBuilder_;
      }

      private eu.m6r.format.openrtb.MbrWin.Win win_ = eu.m6r.format.openrtb.MbrWin.Win.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          eu.m6r.format.openrtb.MbrWin.Win, eu.m6r.format.openrtb.MbrWin.Win.Builder, eu.m6r.format.openrtb.MbrWin.WinOrBuilder> winBuilder_;
      /**
       * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
       *
       * <pre>
       * Mbr: mbr-win.proto.
       * </pre>
       */
      public boolean hasWin() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
       *
       * <pre>
       * Mbr: mbr-win.proto.
       * </pre>
       */
      public eu.m6r.format.openrtb.MbrWin.Win getWin() {
        if (winBuilder_ == null) {
          return win_;
        } else {
          return winBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
       *
       * <pre>
       * Mbr: mbr-win.proto.
       * </pre>
       */
      public Builder setWin(eu.m6r.format.openrtb.MbrWin.Win value) {
        if (winBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          win_ = value;
          onChanged();
        } else {
          winBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
       *
       * <pre>
       * Mbr: mbr-win.proto.
       * </pre>
       */
      public Builder setWin(
          eu.m6r.format.openrtb.MbrWin.Win.Builder builderForValue) {
        if (winBuilder_ == null) {
          win_ = builderForValue.build();
          onChanged();
        } else {
          winBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
       *
       * <pre>
       * Mbr: mbr-win.proto.
       * </pre>
       */
      public Builder mergeWin(eu.m6r.format.openrtb.MbrWin.Win value) {
        if (winBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              win_ != eu.m6r.format.openrtb.MbrWin.Win.getDefaultInstance()) {
            win_ =
              eu.m6r.format.openrtb.MbrWin.Win.newBuilder(win_).mergeFrom(value).buildPartial();
          } else {
            win_ = value;
          }
          onChanged();
        } else {
          winBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
       *
       * <pre>
       * Mbr: mbr-win.proto.
       * </pre>
       */
      public Builder clearWin() {
        if (winBuilder_ == null) {
          win_ = eu.m6r.format.openrtb.MbrWin.Win.getDefaultInstance();
          onChanged();
        } else {
          winBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
       *
       * <pre>
       * Mbr: mbr-win.proto.
       * </pre>
       */
      public eu.m6r.format.openrtb.MbrWin.Win.Builder getWinBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getWinFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
       *
       * <pre>
       * Mbr: mbr-win.proto.
       * </pre>
       */
      public eu.m6r.format.openrtb.MbrWin.WinOrBuilder getWinOrBuilder() {
        if (winBuilder_ != null) {
          return winBuilder_.getMessageOrBuilder();
        } else {
          return win_;
        }
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
       *
       * <pre>
       * Mbr: mbr-win.proto.
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          eu.m6r.format.openrtb.MbrWin.Win, eu.m6r.format.openrtb.MbrWin.Win.Builder, eu.m6r.format.openrtb.MbrWin.WinOrBuilder> 
          getWinFieldBuilder() {
        if (winBuilder_ == null) {
          winBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              eu.m6r.format.openrtb.MbrWin.Win, eu.m6r.format.openrtb.MbrWin.Win.Builder, eu.m6r.format.openrtb.MbrWin.WinOrBuilder>(
                  getWin(),
                  getParentForChildren(),
                  isClean());
          win_ = null;
        }
        return winBuilder_;
      }

      private eu.m6r.format.openrtb.MbrImpression.Impression impression_ = eu.m6r.format.openrtb.MbrImpression.Impression.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          eu.m6r.format.openrtb.MbrImpression.Impression, eu.m6r.format.openrtb.MbrImpression.Impression.Builder, eu.m6r.format.openrtb.MbrImpression.ImpressionOrBuilder> impressionBuilder_;
      /**
       * <code>optional .eu.m6r.format.openrtb.Impression impression = 4;</code>
       *
       * <pre>
       * Mbr: mbr-impression.proto.
       * </pre>
       */
      public boolean hasImpression() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Impression impression = 4;</code>
       *
       * <pre>
       * Mbr: mbr-impression.proto.
       * </pre>
       */
      public eu.m6r.format.openrtb.MbrImpression.Impression getImpression() {
        if (impressionBuilder_ == null) {
          return impression_;
        } else {
          return impressionBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Impression impression = 4;</code>
       *
       * <pre>
       * Mbr: mbr-impression.proto.
       * </pre>
       */
      public Builder setImpression(eu.m6r.format.openrtb.MbrImpression.Impression value) {
        if (impressionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          impression_ = value;
          onChanged();
        } else {
          impressionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Impression impression = 4;</code>
       *
       * <pre>
       * Mbr: mbr-impression.proto.
       * </pre>
       */
      public Builder setImpression(
          eu.m6r.format.openrtb.MbrImpression.Impression.Builder builderForValue) {
        if (impressionBuilder_ == null) {
          impression_ = builderForValue.build();
          onChanged();
        } else {
          impressionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Impression impression = 4;</code>
       *
       * <pre>
       * Mbr: mbr-impression.proto.
       * </pre>
       */
      public Builder mergeImpression(eu.m6r.format.openrtb.MbrImpression.Impression value) {
        if (impressionBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              impression_ != eu.m6r.format.openrtb.MbrImpression.Impression.getDefaultInstance()) {
            impression_ =
              eu.m6r.format.openrtb.MbrImpression.Impression.newBuilder(impression_).mergeFrom(value).buildPartial();
          } else {
            impression_ = value;
          }
          onChanged();
        } else {
          impressionBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Impression impression = 4;</code>
       *
       * <pre>
       * Mbr: mbr-impression.proto.
       * </pre>
       */
      public Builder clearImpression() {
        if (impressionBuilder_ == null) {
          impression_ = eu.m6r.format.openrtb.MbrImpression.Impression.getDefaultInstance();
          onChanged();
        } else {
          impressionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Impression impression = 4;</code>
       *
       * <pre>
       * Mbr: mbr-impression.proto.
       * </pre>
       */
      public eu.m6r.format.openrtb.MbrImpression.Impression.Builder getImpressionBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getImpressionFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Impression impression = 4;</code>
       *
       * <pre>
       * Mbr: mbr-impression.proto.
       * </pre>
       */
      public eu.m6r.format.openrtb.MbrImpression.ImpressionOrBuilder getImpressionOrBuilder() {
        if (impressionBuilder_ != null) {
          return impressionBuilder_.getMessageOrBuilder();
        } else {
          return impression_;
        }
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Impression impression = 4;</code>
       *
       * <pre>
       * Mbr: mbr-impression.proto.
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          eu.m6r.format.openrtb.MbrImpression.Impression, eu.m6r.format.openrtb.MbrImpression.Impression.Builder, eu.m6r.format.openrtb.MbrImpression.ImpressionOrBuilder> 
          getImpressionFieldBuilder() {
        if (impressionBuilder_ == null) {
          impressionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              eu.m6r.format.openrtb.MbrImpression.Impression, eu.m6r.format.openrtb.MbrImpression.Impression.Builder, eu.m6r.format.openrtb.MbrImpression.ImpressionOrBuilder>(
                  getImpression(),
                  getParentForChildren(),
                  isClean());
          impression_ = null;
        }
        return impressionBuilder_;
      }

      private eu.m6r.format.openrtb.MbrClick.Click click_ = eu.m6r.format.openrtb.MbrClick.Click.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          eu.m6r.format.openrtb.MbrClick.Click, eu.m6r.format.openrtb.MbrClick.Click.Builder, eu.m6r.format.openrtb.MbrClick.ClickOrBuilder> clickBuilder_;
      /**
       * <code>optional .eu.m6r.format.openrtb.Click click = 5;</code>
       *
       * <pre>
       * Mbr: mbr-click.proto.
       * </pre>
       */
      public boolean hasClick() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Click click = 5;</code>
       *
       * <pre>
       * Mbr: mbr-click.proto.
       * </pre>
       */
      public eu.m6r.format.openrtb.MbrClick.Click getClick() {
        if (clickBuilder_ == null) {
          return click_;
        } else {
          return clickBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Click click = 5;</code>
       *
       * <pre>
       * Mbr: mbr-click.proto.
       * </pre>
       */
      public Builder setClick(eu.m6r.format.openrtb.MbrClick.Click value) {
        if (clickBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          click_ = value;
          onChanged();
        } else {
          clickBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Click click = 5;</code>
       *
       * <pre>
       * Mbr: mbr-click.proto.
       * </pre>
       */
      public Builder setClick(
          eu.m6r.format.openrtb.MbrClick.Click.Builder builderForValue) {
        if (clickBuilder_ == null) {
          click_ = builderForValue.build();
          onChanged();
        } else {
          clickBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Click click = 5;</code>
       *
       * <pre>
       * Mbr: mbr-click.proto.
       * </pre>
       */
      public Builder mergeClick(eu.m6r.format.openrtb.MbrClick.Click value) {
        if (clickBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              click_ != eu.m6r.format.openrtb.MbrClick.Click.getDefaultInstance()) {
            click_ =
              eu.m6r.format.openrtb.MbrClick.Click.newBuilder(click_).mergeFrom(value).buildPartial();
          } else {
            click_ = value;
          }
          onChanged();
        } else {
          clickBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Click click = 5;</code>
       *
       * <pre>
       * Mbr: mbr-click.proto.
       * </pre>
       */
      public Builder clearClick() {
        if (clickBuilder_ == null) {
          click_ = eu.m6r.format.openrtb.MbrClick.Click.getDefaultInstance();
          onChanged();
        } else {
          clickBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Click click = 5;</code>
       *
       * <pre>
       * Mbr: mbr-click.proto.
       * </pre>
       */
      public eu.m6r.format.openrtb.MbrClick.Click.Builder getClickBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getClickFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Click click = 5;</code>
       *
       * <pre>
       * Mbr: mbr-click.proto.
       * </pre>
       */
      public eu.m6r.format.openrtb.MbrClick.ClickOrBuilder getClickOrBuilder() {
        if (clickBuilder_ != null) {
          return clickBuilder_.getMessageOrBuilder();
        } else {
          return click_;
        }
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Click click = 5;</code>
       *
       * <pre>
       * Mbr: mbr-click.proto.
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          eu.m6r.format.openrtb.MbrClick.Click, eu.m6r.format.openrtb.MbrClick.Click.Builder, eu.m6r.format.openrtb.MbrClick.ClickOrBuilder> 
          getClickFieldBuilder() {
        if (clickBuilder_ == null) {
          clickBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              eu.m6r.format.openrtb.MbrClick.Click, eu.m6r.format.openrtb.MbrClick.Click.Builder, eu.m6r.format.openrtb.MbrClick.ClickOrBuilder>(
                  getClick(),
                  getParentForChildren(),
                  isClean());
          click_ = null;
        }
        return clickBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:eu.m6r.format.openrtb.JoinedClick)
    }

    static {
      defaultInstance = new JoinedClick(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:eu.m6r.format.openrtb.JoinedClick)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_m6r_format_openrtb_Click_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_m6r_format_openrtb_Click_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_m6r_format_openrtb_JoinedClick_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_m6r_format_openrtb_JoinedClick_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017mbr-click.proto\022\025eu.m6r.format.openrtb" +
      "\032\020mbr-amount.proto\032\024mbr-impression.proto" +
      "\032\rmbr-win.proto\032\ropenrtb.proto\"~\n\005Click\022" +
      "/\n\007request\030\001 \001(\0132\036.com.google.openrtb.Bi" +
      "dRequest\022\024\n\014impressionid\030\002 \001(\t\022.\n\007revenu" +
      "e\030\003 \001(\0132\035.eu.m6r.format.openrtb.Amount\"\204" +
      "\002\n\013JoinedClick\0222\n\nbidrequest\030\001 \001(\0132\036.com" +
      ".google.openrtb.BidRequest\0224\n\013bidrespons" +
      "e\030\002 \001(\0132\037.com.google.openrtb.BidResponse" +
      "\022\'\n\003win\030\003 \001(\0132\032.eu.m6r.format.openrtb.Wi",
      "n\0225\n\nimpression\030\004 \001(\0132!.eu.m6r.format.op" +
      "enrtb.Impression\022+\n\005click\030\005 \001(\0132\034.eu.m6r" +
      ".format.openrtb.Click"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.adscale.format.opertb.AmountMessage.getDescriptor(),
          eu.m6r.format.openrtb.MbrImpression.getDescriptor(),
          eu.m6r.format.openrtb.MbrWin.getDescriptor(),
          com.google.openrtb.OpenRtb.getDescriptor(),
        }, assigner);
    internal_static_eu_m6r_format_openrtb_Click_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eu_m6r_format_openrtb_Click_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eu_m6r_format_openrtb_Click_descriptor,
        new java.lang.String[] { "Request", "Impressionid", "Revenue", });
    internal_static_eu_m6r_format_openrtb_JoinedClick_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_eu_m6r_format_openrtb_JoinedClick_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eu_m6r_format_openrtb_JoinedClick_descriptor,
        new java.lang.String[] { "Bidrequest", "Bidresponse", "Win", "Impression", "Click", });
    org.adscale.format.opertb.AmountMessage.getDescriptor();
    eu.m6r.format.openrtb.MbrImpression.getDescriptor();
    eu.m6r.format.openrtb.MbrWin.getDescriptor();
    com.google.openrtb.OpenRtb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
