// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mbr-win.proto

package eu.m6r.format.openrtb;

public final class MbrWin {
  private MbrWin() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WinOrBuilder extends
      // @@protoc_insertion_point(interface_extends:eu.m6r.format.openrtb.Win)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
     *
     * <pre>
     * Mbr: Contains all data regarding the request.
     * </pre>
     */
    boolean hasRequest();
    /**
     * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
     *
     * <pre>
     * Mbr: Contains all data regarding the request.
     * </pre>
     */
    com.google.openrtb.OpenRtb.BidRequest getRequest();
    /**
     * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
     *
     * <pre>
     * Mbr: Contains all data regarding the request.
     * </pre>
     */
    com.google.openrtb.OpenRtb.BidRequestOrBuilder getRequestOrBuilder();

    /**
     * <code>optional string bidid = 2;</code>
     *
     * <pre>
     * Mbr: The id stored in the corresponding Bid object.
     * </pre>
     */
    boolean hasBidid();
    /**
     * <code>optional string bidid = 2;</code>
     *
     * <pre>
     * Mbr: The id stored in the corresponding Bid object.
     * </pre>
     */
    java.lang.String getBidid();
    /**
     * <code>optional string bidid = 2;</code>
     *
     * <pre>
     * Mbr: The id stored in the corresponding Bid object.
     * </pre>
     */
    com.google.protobuf.ByteString
        getBididBytes();

    /**
     * <code>optional .eu.m6r.format.openrtb.Amount campaignprice = 3;</code>
     *
     * <pre>
     * Mbr: Actual price paid in the campaign currency.
     * </pre>
     */
    boolean hasCampaignprice();
    /**
     * <code>optional .eu.m6r.format.openrtb.Amount campaignprice = 3;</code>
     *
     * <pre>
     * Mbr: Actual price paid in the campaign currency.
     * </pre>
     */
    org.adscale.format.opertb.AmountMessage.Amount getCampaignprice();
    /**
     * <code>optional .eu.m6r.format.openrtb.Amount campaignprice = 3;</code>
     *
     * <pre>
     * Mbr: Actual price paid in the campaign currency.
     * </pre>
     */
    org.adscale.format.opertb.AmountMessage.AmountOrBuilder getCampaignpriceOrBuilder();

    /**
     * <code>optional .eu.m6r.format.openrtb.Amount exchangeprice = 4;</code>
     *
     * <pre>
     * Mbr: Actual price paid in the exchange currency.
     * </pre>
     */
    boolean hasExchangeprice();
    /**
     * <code>optional .eu.m6r.format.openrtb.Amount exchangeprice = 4;</code>
     *
     * <pre>
     * Mbr: Actual price paid in the exchange currency.
     * </pre>
     */
    org.adscale.format.opertb.AmountMessage.Amount getExchangeprice();
    /**
     * <code>optional .eu.m6r.format.openrtb.Amount exchangeprice = 4;</code>
     *
     * <pre>
     * Mbr: Actual price paid in the exchange currency.
     * </pre>
     */
    org.adscale.format.opertb.AmountMessage.AmountOrBuilder getExchangepriceOrBuilder();
  }
  /**
   * Protobuf type {@code eu.m6r.format.openrtb.Win}
   *
   * <pre>
   * Mbr: Win specific values and request.
   * </pre>
   */
  public static final class Win extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:eu.m6r.format.openrtb.Win)
      WinOrBuilder {
    // Use Win.newBuilder() to construct.
    private Win(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Win(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Win defaultInstance;
    public static Win getDefaultInstance() {
      return defaultInstance;
    }

    public Win getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Win(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.openrtb.OpenRtb.BidRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = request_.toBuilder();
              }
              request_ = input.readMessage(com.google.openrtb.OpenRtb.BidRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(request_);
                request_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              bidid_ = bs;
              break;
            }
            case 26: {
              org.adscale.format.opertb.AmountMessage.Amount.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = campaignprice_.toBuilder();
              }
              campaignprice_ = input.readMessage(org.adscale.format.opertb.AmountMessage.Amount.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(campaignprice_);
                campaignprice_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              org.adscale.format.opertb.AmountMessage.Amount.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = exchangeprice_.toBuilder();
              }
              exchangeprice_ = input.readMessage(org.adscale.format.opertb.AmountMessage.Amount.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(exchangeprice_);
                exchangeprice_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.m6r.format.openrtb.MbrWin.internal_static_eu_m6r_format_openrtb_Win_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.m6r.format.openrtb.MbrWin.internal_static_eu_m6r_format_openrtb_Win_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.m6r.format.openrtb.MbrWin.Win.class, eu.m6r.format.openrtb.MbrWin.Win.Builder.class);
    }

    public static com.google.protobuf.Parser<Win> PARSER =
        new com.google.protobuf.AbstractParser<Win>() {
      public Win parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Win(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Win> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int REQUEST_FIELD_NUMBER = 1;
    private com.google.openrtb.OpenRtb.BidRequest request_;
    /**
     * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
     *
     * <pre>
     * Mbr: Contains all data regarding the request.
     * </pre>
     */
    public boolean hasRequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
     *
     * <pre>
     * Mbr: Contains all data regarding the request.
     * </pre>
     */
    public com.google.openrtb.OpenRtb.BidRequest getRequest() {
      return request_;
    }
    /**
     * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
     *
     * <pre>
     * Mbr: Contains all data regarding the request.
     * </pre>
     */
    public com.google.openrtb.OpenRtb.BidRequestOrBuilder getRequestOrBuilder() {
      return request_;
    }

    public static final int BIDID_FIELD_NUMBER = 2;
    private java.lang.Object bidid_;
    /**
     * <code>optional string bidid = 2;</code>
     *
     * <pre>
     * Mbr: The id stored in the corresponding Bid object.
     * </pre>
     */
    public boolean hasBidid() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string bidid = 2;</code>
     *
     * <pre>
     * Mbr: The id stored in the corresponding Bid object.
     * </pre>
     */
    public java.lang.String getBidid() {
      java.lang.Object ref = bidid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          bidid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string bidid = 2;</code>
     *
     * <pre>
     * Mbr: The id stored in the corresponding Bid object.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getBididBytes() {
      java.lang.Object ref = bidid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bidid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CAMPAIGNPRICE_FIELD_NUMBER = 3;
    private org.adscale.format.opertb.AmountMessage.Amount campaignprice_;
    /**
     * <code>optional .eu.m6r.format.openrtb.Amount campaignprice = 3;</code>
     *
     * <pre>
     * Mbr: Actual price paid in the campaign currency.
     * </pre>
     */
    public boolean hasCampaignprice() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .eu.m6r.format.openrtb.Amount campaignprice = 3;</code>
     *
     * <pre>
     * Mbr: Actual price paid in the campaign currency.
     * </pre>
     */
    public org.adscale.format.opertb.AmountMessage.Amount getCampaignprice() {
      return campaignprice_;
    }
    /**
     * <code>optional .eu.m6r.format.openrtb.Amount campaignprice = 3;</code>
     *
     * <pre>
     * Mbr: Actual price paid in the campaign currency.
     * </pre>
     */
    public org.adscale.format.opertb.AmountMessage.AmountOrBuilder getCampaignpriceOrBuilder() {
      return campaignprice_;
    }

    public static final int EXCHANGEPRICE_FIELD_NUMBER = 4;
    private org.adscale.format.opertb.AmountMessage.Amount exchangeprice_;
    /**
     * <code>optional .eu.m6r.format.openrtb.Amount exchangeprice = 4;</code>
     *
     * <pre>
     * Mbr: Actual price paid in the exchange currency.
     * </pre>
     */
    public boolean hasExchangeprice() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .eu.m6r.format.openrtb.Amount exchangeprice = 4;</code>
     *
     * <pre>
     * Mbr: Actual price paid in the exchange currency.
     * </pre>
     */
    public org.adscale.format.opertb.AmountMessage.Amount getExchangeprice() {
      return exchangeprice_;
    }
    /**
     * <code>optional .eu.m6r.format.openrtb.Amount exchangeprice = 4;</code>
     *
     * <pre>
     * Mbr: Actual price paid in the exchange currency.
     * </pre>
     */
    public org.adscale.format.opertb.AmountMessage.AmountOrBuilder getExchangepriceOrBuilder() {
      return exchangeprice_;
    }

    private void initFields() {
      request_ = com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance();
      bidid_ = "";
      campaignprice_ = org.adscale.format.opertb.AmountMessage.Amount.getDefaultInstance();
      exchangeprice_ = org.adscale.format.opertb.AmountMessage.Amount.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasRequest()) {
        if (!getRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, request_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getBididBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, campaignprice_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, exchangeprice_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, request_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getBididBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, campaignprice_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, exchangeprice_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static eu.m6r.format.openrtb.MbrWin.Win parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.m6r.format.openrtb.MbrWin.Win parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.m6r.format.openrtb.MbrWin.Win parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.m6r.format.openrtb.MbrWin.Win parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.m6r.format.openrtb.MbrWin.Win parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.m6r.format.openrtb.MbrWin.Win parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static eu.m6r.format.openrtb.MbrWin.Win parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static eu.m6r.format.openrtb.MbrWin.Win parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static eu.m6r.format.openrtb.MbrWin.Win parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.m6r.format.openrtb.MbrWin.Win parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.m6r.format.openrtb.MbrWin.Win prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eu.m6r.format.openrtb.Win}
     *
     * <pre>
     * Mbr: Win specific values and request.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:eu.m6r.format.openrtb.Win)
        eu.m6r.format.openrtb.MbrWin.WinOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.m6r.format.openrtb.MbrWin.internal_static_eu_m6r_format_openrtb_Win_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.m6r.format.openrtb.MbrWin.internal_static_eu_m6r_format_openrtb_Win_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eu.m6r.format.openrtb.MbrWin.Win.class, eu.m6r.format.openrtb.MbrWin.Win.Builder.class);
      }

      // Construct using eu.m6r.format.openrtb.MbrWin.Win.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRequestFieldBuilder();
          getCampaignpriceFieldBuilder();
          getExchangepriceFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (requestBuilder_ == null) {
          request_ = com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        bidid_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (campaignpriceBuilder_ == null) {
          campaignprice_ = org.adscale.format.opertb.AmountMessage.Amount.getDefaultInstance();
        } else {
          campaignpriceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        if (exchangepriceBuilder_ == null) {
          exchangeprice_ = org.adscale.format.opertb.AmountMessage.Amount.getDefaultInstance();
        } else {
          exchangepriceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.m6r.format.openrtb.MbrWin.internal_static_eu_m6r_format_openrtb_Win_descriptor;
      }

      public eu.m6r.format.openrtb.MbrWin.Win getDefaultInstanceForType() {
        return eu.m6r.format.openrtb.MbrWin.Win.getDefaultInstance();
      }

      public eu.m6r.format.openrtb.MbrWin.Win build() {
        eu.m6r.format.openrtb.MbrWin.Win result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public eu.m6r.format.openrtb.MbrWin.Win buildPartial() {
        eu.m6r.format.openrtb.MbrWin.Win result = new eu.m6r.format.openrtb.MbrWin.Win(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (requestBuilder_ == null) {
          result.request_ = request_;
        } else {
          result.request_ = requestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.bidid_ = bidid_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (campaignpriceBuilder_ == null) {
          result.campaignprice_ = campaignprice_;
        } else {
          result.campaignprice_ = campaignpriceBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (exchangepriceBuilder_ == null) {
          result.exchangeprice_ = exchangeprice_;
        } else {
          result.exchangeprice_ = exchangepriceBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.m6r.format.openrtb.MbrWin.Win) {
          return mergeFrom((eu.m6r.format.openrtb.MbrWin.Win)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eu.m6r.format.openrtb.MbrWin.Win other) {
        if (other == eu.m6r.format.openrtb.MbrWin.Win.getDefaultInstance()) return this;
        if (other.hasRequest()) {
          mergeRequest(other.getRequest());
        }
        if (other.hasBidid()) {
          bitField0_ |= 0x00000002;
          bidid_ = other.bidid_;
          onChanged();
        }
        if (other.hasCampaignprice()) {
          mergeCampaignprice(other.getCampaignprice());
        }
        if (other.hasExchangeprice()) {
          mergeExchangeprice(other.getExchangeprice());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasRequest()) {
          if (!getRequest().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eu.m6r.format.openrtb.MbrWin.Win parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eu.m6r.format.openrtb.MbrWin.Win) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.openrtb.OpenRtb.BidRequest request_ = com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.google.openrtb.OpenRtb.BidRequest, com.google.openrtb.OpenRtb.BidRequest.Builder, com.google.openrtb.OpenRtb.BidRequestOrBuilder> requestBuilder_;
      /**
       * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
       *
       * <pre>
       * Mbr: Contains all data regarding the request.
       * </pre>
       */
      public boolean hasRequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
       *
       * <pre>
       * Mbr: Contains all data regarding the request.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidRequest getRequest() {
        if (requestBuilder_ == null) {
          return request_;
        } else {
          return requestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
       *
       * <pre>
       * Mbr: Contains all data regarding the request.
       * </pre>
       */
      public Builder setRequest(com.google.openrtb.OpenRtb.BidRequest value) {
        if (requestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          request_ = value;
          onChanged();
        } else {
          requestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
       *
       * <pre>
       * Mbr: Contains all data regarding the request.
       * </pre>
       */
      public Builder setRequest(
          com.google.openrtb.OpenRtb.BidRequest.Builder builderForValue) {
        if (requestBuilder_ == null) {
          request_ = builderForValue.build();
          onChanged();
        } else {
          requestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
       *
       * <pre>
       * Mbr: Contains all data regarding the request.
       * </pre>
       */
      public Builder mergeRequest(com.google.openrtb.OpenRtb.BidRequest value) {
        if (requestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              request_ != com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance()) {
            request_ =
              com.google.openrtb.OpenRtb.BidRequest.newBuilder(request_).mergeFrom(value).buildPartial();
          } else {
            request_ = value;
          }
          onChanged();
        } else {
          requestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
       *
       * <pre>
       * Mbr: Contains all data regarding the request.
       * </pre>
       */
      public Builder clearRequest() {
        if (requestBuilder_ == null) {
          request_ = com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance();
          onChanged();
        } else {
          requestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
       *
       * <pre>
       * Mbr: Contains all data regarding the request.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidRequest.Builder getRequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
       *
       * <pre>
       * Mbr: Contains all data regarding the request.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidRequestOrBuilder getRequestOrBuilder() {
        if (requestBuilder_ != null) {
          return requestBuilder_.getMessageOrBuilder();
        } else {
          return request_;
        }
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest request = 1;</code>
       *
       * <pre>
       * Mbr: Contains all data regarding the request.
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.openrtb.OpenRtb.BidRequest, com.google.openrtb.OpenRtb.BidRequest.Builder, com.google.openrtb.OpenRtb.BidRequestOrBuilder> 
          getRequestFieldBuilder() {
        if (requestBuilder_ == null) {
          requestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.openrtb.OpenRtb.BidRequest, com.google.openrtb.OpenRtb.BidRequest.Builder, com.google.openrtb.OpenRtb.BidRequestOrBuilder>(
                  getRequest(),
                  getParentForChildren(),
                  isClean());
          request_ = null;
        }
        return requestBuilder_;
      }

      private java.lang.Object bidid_ = "";
      /**
       * <code>optional string bidid = 2;</code>
       *
       * <pre>
       * Mbr: The id stored in the corresponding Bid object.
       * </pre>
       */
      public boolean hasBidid() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string bidid = 2;</code>
       *
       * <pre>
       * Mbr: The id stored in the corresponding Bid object.
       * </pre>
       */
      public java.lang.String getBidid() {
        java.lang.Object ref = bidid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            bidid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string bidid = 2;</code>
       *
       * <pre>
       * Mbr: The id stored in the corresponding Bid object.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getBididBytes() {
        java.lang.Object ref = bidid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bidid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string bidid = 2;</code>
       *
       * <pre>
       * Mbr: The id stored in the corresponding Bid object.
       * </pre>
       */
      public Builder setBidid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        bidid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string bidid = 2;</code>
       *
       * <pre>
       * Mbr: The id stored in the corresponding Bid object.
       * </pre>
       */
      public Builder clearBidid() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bidid_ = getDefaultInstance().getBidid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string bidid = 2;</code>
       *
       * <pre>
       * Mbr: The id stored in the corresponding Bid object.
       * </pre>
       */
      public Builder setBididBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        bidid_ = value;
        onChanged();
        return this;
      }

      private org.adscale.format.opertb.AmountMessage.Amount campaignprice_ = org.adscale.format.opertb.AmountMessage.Amount.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.adscale.format.opertb.AmountMessage.Amount, org.adscale.format.opertb.AmountMessage.Amount.Builder, org.adscale.format.opertb.AmountMessage.AmountOrBuilder> campaignpriceBuilder_;
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount campaignprice = 3;</code>
       *
       * <pre>
       * Mbr: Actual price paid in the campaign currency.
       * </pre>
       */
      public boolean hasCampaignprice() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount campaignprice = 3;</code>
       *
       * <pre>
       * Mbr: Actual price paid in the campaign currency.
       * </pre>
       */
      public org.adscale.format.opertb.AmountMessage.Amount getCampaignprice() {
        if (campaignpriceBuilder_ == null) {
          return campaignprice_;
        } else {
          return campaignpriceBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount campaignprice = 3;</code>
       *
       * <pre>
       * Mbr: Actual price paid in the campaign currency.
       * </pre>
       */
      public Builder setCampaignprice(org.adscale.format.opertb.AmountMessage.Amount value) {
        if (campaignpriceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          campaignprice_ = value;
          onChanged();
        } else {
          campaignpriceBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount campaignprice = 3;</code>
       *
       * <pre>
       * Mbr: Actual price paid in the campaign currency.
       * </pre>
       */
      public Builder setCampaignprice(
          org.adscale.format.opertb.AmountMessage.Amount.Builder builderForValue) {
        if (campaignpriceBuilder_ == null) {
          campaignprice_ = builderForValue.build();
          onChanged();
        } else {
          campaignpriceBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount campaignprice = 3;</code>
       *
       * <pre>
       * Mbr: Actual price paid in the campaign currency.
       * </pre>
       */
      public Builder mergeCampaignprice(org.adscale.format.opertb.AmountMessage.Amount value) {
        if (campaignpriceBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              campaignprice_ != org.adscale.format.opertb.AmountMessage.Amount.getDefaultInstance()) {
            campaignprice_ =
              org.adscale.format.opertb.AmountMessage.Amount.newBuilder(campaignprice_).mergeFrom(value).buildPartial();
          } else {
            campaignprice_ = value;
          }
          onChanged();
        } else {
          campaignpriceBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount campaignprice = 3;</code>
       *
       * <pre>
       * Mbr: Actual price paid in the campaign currency.
       * </pre>
       */
      public Builder clearCampaignprice() {
        if (campaignpriceBuilder_ == null) {
          campaignprice_ = org.adscale.format.opertb.AmountMessage.Amount.getDefaultInstance();
          onChanged();
        } else {
          campaignpriceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount campaignprice = 3;</code>
       *
       * <pre>
       * Mbr: Actual price paid in the campaign currency.
       * </pre>
       */
      public org.adscale.format.opertb.AmountMessage.Amount.Builder getCampaignpriceBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getCampaignpriceFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount campaignprice = 3;</code>
       *
       * <pre>
       * Mbr: Actual price paid in the campaign currency.
       * </pre>
       */
      public org.adscale.format.opertb.AmountMessage.AmountOrBuilder getCampaignpriceOrBuilder() {
        if (campaignpriceBuilder_ != null) {
          return campaignpriceBuilder_.getMessageOrBuilder();
        } else {
          return campaignprice_;
        }
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount campaignprice = 3;</code>
       *
       * <pre>
       * Mbr: Actual price paid in the campaign currency.
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.adscale.format.opertb.AmountMessage.Amount, org.adscale.format.opertb.AmountMessage.Amount.Builder, org.adscale.format.opertb.AmountMessage.AmountOrBuilder> 
          getCampaignpriceFieldBuilder() {
        if (campaignpriceBuilder_ == null) {
          campaignpriceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.adscale.format.opertb.AmountMessage.Amount, org.adscale.format.opertb.AmountMessage.Amount.Builder, org.adscale.format.opertb.AmountMessage.AmountOrBuilder>(
                  getCampaignprice(),
                  getParentForChildren(),
                  isClean());
          campaignprice_ = null;
        }
        return campaignpriceBuilder_;
      }

      private org.adscale.format.opertb.AmountMessage.Amount exchangeprice_ = org.adscale.format.opertb.AmountMessage.Amount.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.adscale.format.opertb.AmountMessage.Amount, org.adscale.format.opertb.AmountMessage.Amount.Builder, org.adscale.format.opertb.AmountMessage.AmountOrBuilder> exchangepriceBuilder_;
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount exchangeprice = 4;</code>
       *
       * <pre>
       * Mbr: Actual price paid in the exchange currency.
       * </pre>
       */
      public boolean hasExchangeprice() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount exchangeprice = 4;</code>
       *
       * <pre>
       * Mbr: Actual price paid in the exchange currency.
       * </pre>
       */
      public org.adscale.format.opertb.AmountMessage.Amount getExchangeprice() {
        if (exchangepriceBuilder_ == null) {
          return exchangeprice_;
        } else {
          return exchangepriceBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount exchangeprice = 4;</code>
       *
       * <pre>
       * Mbr: Actual price paid in the exchange currency.
       * </pre>
       */
      public Builder setExchangeprice(org.adscale.format.opertb.AmountMessage.Amount value) {
        if (exchangepriceBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          exchangeprice_ = value;
          onChanged();
        } else {
          exchangepriceBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount exchangeprice = 4;</code>
       *
       * <pre>
       * Mbr: Actual price paid in the exchange currency.
       * </pre>
       */
      public Builder setExchangeprice(
          org.adscale.format.opertb.AmountMessage.Amount.Builder builderForValue) {
        if (exchangepriceBuilder_ == null) {
          exchangeprice_ = builderForValue.build();
          onChanged();
        } else {
          exchangepriceBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount exchangeprice = 4;</code>
       *
       * <pre>
       * Mbr: Actual price paid in the exchange currency.
       * </pre>
       */
      public Builder mergeExchangeprice(org.adscale.format.opertb.AmountMessage.Amount value) {
        if (exchangepriceBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              exchangeprice_ != org.adscale.format.opertb.AmountMessage.Amount.getDefaultInstance()) {
            exchangeprice_ =
              org.adscale.format.opertb.AmountMessage.Amount.newBuilder(exchangeprice_).mergeFrom(value).buildPartial();
          } else {
            exchangeprice_ = value;
          }
          onChanged();
        } else {
          exchangepriceBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount exchangeprice = 4;</code>
       *
       * <pre>
       * Mbr: Actual price paid in the exchange currency.
       * </pre>
       */
      public Builder clearExchangeprice() {
        if (exchangepriceBuilder_ == null) {
          exchangeprice_ = org.adscale.format.opertb.AmountMessage.Amount.getDefaultInstance();
          onChanged();
        } else {
          exchangepriceBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount exchangeprice = 4;</code>
       *
       * <pre>
       * Mbr: Actual price paid in the exchange currency.
       * </pre>
       */
      public org.adscale.format.opertb.AmountMessage.Amount.Builder getExchangepriceBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getExchangepriceFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount exchangeprice = 4;</code>
       *
       * <pre>
       * Mbr: Actual price paid in the exchange currency.
       * </pre>
       */
      public org.adscale.format.opertb.AmountMessage.AmountOrBuilder getExchangepriceOrBuilder() {
        if (exchangepriceBuilder_ != null) {
          return exchangepriceBuilder_.getMessageOrBuilder();
        } else {
          return exchangeprice_;
        }
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Amount exchangeprice = 4;</code>
       *
       * <pre>
       * Mbr: Actual price paid in the exchange currency.
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.adscale.format.opertb.AmountMessage.Amount, org.adscale.format.opertb.AmountMessage.Amount.Builder, org.adscale.format.opertb.AmountMessage.AmountOrBuilder> 
          getExchangepriceFieldBuilder() {
        if (exchangepriceBuilder_ == null) {
          exchangepriceBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.adscale.format.opertb.AmountMessage.Amount, org.adscale.format.opertb.AmountMessage.Amount.Builder, org.adscale.format.opertb.AmountMessage.AmountOrBuilder>(
                  getExchangeprice(),
                  getParentForChildren(),
                  isClean());
          exchangeprice_ = null;
        }
        return exchangepriceBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:eu.m6r.format.openrtb.Win)
    }

    static {
      defaultInstance = new Win(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:eu.m6r.format.openrtb.Win)
  }

  public interface JoinedWinOrBuilder extends
      // @@protoc_insertion_point(interface_extends:eu.m6r.format.openrtb.JoinedWin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
     *
     * <pre>
     * Mbr: mbr-bid-request.proto.
     * </pre>
     */
    boolean hasBidrequest();
    /**
     * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
     *
     * <pre>
     * Mbr: mbr-bid-request.proto.
     * </pre>
     */
    com.google.openrtb.OpenRtb.BidRequest getBidrequest();
    /**
     * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
     *
     * <pre>
     * Mbr: mbr-bid-request.proto.
     * </pre>
     */
    com.google.openrtb.OpenRtb.BidRequestOrBuilder getBidrequestOrBuilder();

    /**
     * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
     *
     * <pre>
     * Mbr: mbr-bid-response.proto.
     * </pre>
     */
    boolean hasBidresponse();
    /**
     * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
     *
     * <pre>
     * Mbr: mbr-bid-response.proto.
     * </pre>
     */
    com.google.openrtb.OpenRtb.BidResponse getBidresponse();
    /**
     * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
     *
     * <pre>
     * Mbr: mbr-bid-response.proto.
     * </pre>
     */
    com.google.openrtb.OpenRtb.BidResponseOrBuilder getBidresponseOrBuilder();

    /**
     * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
     *
     * <pre>
     * Mbr: mbr-win.proto.
     * </pre>
     */
    boolean hasWin();
    /**
     * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
     *
     * <pre>
     * Mbr: mbr-win.proto.
     * </pre>
     */
    eu.m6r.format.openrtb.MbrWin.Win getWin();
    /**
     * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
     *
     * <pre>
     * Mbr: mbr-win.proto.
     * </pre>
     */
    eu.m6r.format.openrtb.MbrWin.WinOrBuilder getWinOrBuilder();
  }
  /**
   * Protobuf type {@code eu.m6r.format.openrtb.JoinedWin}
   *
   * <pre>
   * Mbr: The event history of an win.
   * </pre>
   */
  public static final class JoinedWin extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:eu.m6r.format.openrtb.JoinedWin)
      JoinedWinOrBuilder {
    // Use JoinedWin.newBuilder() to construct.
    private JoinedWin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private JoinedWin(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final JoinedWin defaultInstance;
    public static JoinedWin getDefaultInstance() {
      return defaultInstance;
    }

    public JoinedWin getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private JoinedWin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.openrtb.OpenRtb.BidRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = bidrequest_.toBuilder();
              }
              bidrequest_ = input.readMessage(com.google.openrtb.OpenRtb.BidRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bidrequest_);
                bidrequest_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              com.google.openrtb.OpenRtb.BidResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = bidresponse_.toBuilder();
              }
              bidresponse_ = input.readMessage(com.google.openrtb.OpenRtb.BidResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(bidresponse_);
                bidresponse_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              eu.m6r.format.openrtb.MbrWin.Win.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = win_.toBuilder();
              }
              win_ = input.readMessage(eu.m6r.format.openrtb.MbrWin.Win.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(win_);
                win_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return eu.m6r.format.openrtb.MbrWin.internal_static_eu_m6r_format_openrtb_JoinedWin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return eu.m6r.format.openrtb.MbrWin.internal_static_eu_m6r_format_openrtb_JoinedWin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              eu.m6r.format.openrtb.MbrWin.JoinedWin.class, eu.m6r.format.openrtb.MbrWin.JoinedWin.Builder.class);
    }

    public static com.google.protobuf.Parser<JoinedWin> PARSER =
        new com.google.protobuf.AbstractParser<JoinedWin>() {
      public JoinedWin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JoinedWin(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<JoinedWin> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BIDREQUEST_FIELD_NUMBER = 1;
    private com.google.openrtb.OpenRtb.BidRequest bidrequest_;
    /**
     * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
     *
     * <pre>
     * Mbr: mbr-bid-request.proto.
     * </pre>
     */
    public boolean hasBidrequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
     *
     * <pre>
     * Mbr: mbr-bid-request.proto.
     * </pre>
     */
    public com.google.openrtb.OpenRtb.BidRequest getBidrequest() {
      return bidrequest_;
    }
    /**
     * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
     *
     * <pre>
     * Mbr: mbr-bid-request.proto.
     * </pre>
     */
    public com.google.openrtb.OpenRtb.BidRequestOrBuilder getBidrequestOrBuilder() {
      return bidrequest_;
    }

    public static final int BIDRESPONSE_FIELD_NUMBER = 2;
    private com.google.openrtb.OpenRtb.BidResponse bidresponse_;
    /**
     * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
     *
     * <pre>
     * Mbr: mbr-bid-response.proto.
     * </pre>
     */
    public boolean hasBidresponse() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
     *
     * <pre>
     * Mbr: mbr-bid-response.proto.
     * </pre>
     */
    public com.google.openrtb.OpenRtb.BidResponse getBidresponse() {
      return bidresponse_;
    }
    /**
     * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
     *
     * <pre>
     * Mbr: mbr-bid-response.proto.
     * </pre>
     */
    public com.google.openrtb.OpenRtb.BidResponseOrBuilder getBidresponseOrBuilder() {
      return bidresponse_;
    }

    public static final int WIN_FIELD_NUMBER = 3;
    private eu.m6r.format.openrtb.MbrWin.Win win_;
    /**
     * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
     *
     * <pre>
     * Mbr: mbr-win.proto.
     * </pre>
     */
    public boolean hasWin() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
     *
     * <pre>
     * Mbr: mbr-win.proto.
     * </pre>
     */
    public eu.m6r.format.openrtb.MbrWin.Win getWin() {
      return win_;
    }
    /**
     * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
     *
     * <pre>
     * Mbr: mbr-win.proto.
     * </pre>
     */
    public eu.m6r.format.openrtb.MbrWin.WinOrBuilder getWinOrBuilder() {
      return win_;
    }

    private void initFields() {
      bidrequest_ = com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance();
      bidresponse_ = com.google.openrtb.OpenRtb.BidResponse.getDefaultInstance();
      win_ = eu.m6r.format.openrtb.MbrWin.Win.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasBidrequest()) {
        if (!getBidrequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasBidresponse()) {
        if (!getBidresponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasWin()) {
        if (!getWin().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, bidrequest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, bidresponse_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, win_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, bidrequest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, bidresponse_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, win_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static eu.m6r.format.openrtb.MbrWin.JoinedWin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.m6r.format.openrtb.MbrWin.JoinedWin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.m6r.format.openrtb.MbrWin.JoinedWin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static eu.m6r.format.openrtb.MbrWin.JoinedWin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static eu.m6r.format.openrtb.MbrWin.JoinedWin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.m6r.format.openrtb.MbrWin.JoinedWin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static eu.m6r.format.openrtb.MbrWin.JoinedWin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static eu.m6r.format.openrtb.MbrWin.JoinedWin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static eu.m6r.format.openrtb.MbrWin.JoinedWin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static eu.m6r.format.openrtb.MbrWin.JoinedWin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(eu.m6r.format.openrtb.MbrWin.JoinedWin prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eu.m6r.format.openrtb.JoinedWin}
     *
     * <pre>
     * Mbr: The event history of an win.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:eu.m6r.format.openrtb.JoinedWin)
        eu.m6r.format.openrtb.MbrWin.JoinedWinOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return eu.m6r.format.openrtb.MbrWin.internal_static_eu_m6r_format_openrtb_JoinedWin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return eu.m6r.format.openrtb.MbrWin.internal_static_eu_m6r_format_openrtb_JoinedWin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                eu.m6r.format.openrtb.MbrWin.JoinedWin.class, eu.m6r.format.openrtb.MbrWin.JoinedWin.Builder.class);
      }

      // Construct using eu.m6r.format.openrtb.MbrWin.JoinedWin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBidrequestFieldBuilder();
          getBidresponseFieldBuilder();
          getWinFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (bidrequestBuilder_ == null) {
          bidrequest_ = com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance();
        } else {
          bidrequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (bidresponseBuilder_ == null) {
          bidresponse_ = com.google.openrtb.OpenRtb.BidResponse.getDefaultInstance();
        } else {
          bidresponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (winBuilder_ == null) {
          win_ = eu.m6r.format.openrtb.MbrWin.Win.getDefaultInstance();
        } else {
          winBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return eu.m6r.format.openrtb.MbrWin.internal_static_eu_m6r_format_openrtb_JoinedWin_descriptor;
      }

      public eu.m6r.format.openrtb.MbrWin.JoinedWin getDefaultInstanceForType() {
        return eu.m6r.format.openrtb.MbrWin.JoinedWin.getDefaultInstance();
      }

      public eu.m6r.format.openrtb.MbrWin.JoinedWin build() {
        eu.m6r.format.openrtb.MbrWin.JoinedWin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public eu.m6r.format.openrtb.MbrWin.JoinedWin buildPartial() {
        eu.m6r.format.openrtb.MbrWin.JoinedWin result = new eu.m6r.format.openrtb.MbrWin.JoinedWin(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (bidrequestBuilder_ == null) {
          result.bidrequest_ = bidrequest_;
        } else {
          result.bidrequest_ = bidrequestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (bidresponseBuilder_ == null) {
          result.bidresponse_ = bidresponse_;
        } else {
          result.bidresponse_ = bidresponseBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (winBuilder_ == null) {
          result.win_ = win_;
        } else {
          result.win_ = winBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof eu.m6r.format.openrtb.MbrWin.JoinedWin) {
          return mergeFrom((eu.m6r.format.openrtb.MbrWin.JoinedWin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(eu.m6r.format.openrtb.MbrWin.JoinedWin other) {
        if (other == eu.m6r.format.openrtb.MbrWin.JoinedWin.getDefaultInstance()) return this;
        if (other.hasBidrequest()) {
          mergeBidrequest(other.getBidrequest());
        }
        if (other.hasBidresponse()) {
          mergeBidresponse(other.getBidresponse());
        }
        if (other.hasWin()) {
          mergeWin(other.getWin());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasBidrequest()) {
          if (!getBidrequest().isInitialized()) {
            
            return false;
          }
        }
        if (hasBidresponse()) {
          if (!getBidresponse().isInitialized()) {
            
            return false;
          }
        }
        if (hasWin()) {
          if (!getWin().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        eu.m6r.format.openrtb.MbrWin.JoinedWin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (eu.m6r.format.openrtb.MbrWin.JoinedWin) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.openrtb.OpenRtb.BidRequest bidrequest_ = com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.google.openrtb.OpenRtb.BidRequest, com.google.openrtb.OpenRtb.BidRequest.Builder, com.google.openrtb.OpenRtb.BidRequestOrBuilder> bidrequestBuilder_;
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public boolean hasBidrequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidRequest getBidrequest() {
        if (bidrequestBuilder_ == null) {
          return bidrequest_;
        } else {
          return bidrequestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public Builder setBidrequest(com.google.openrtb.OpenRtb.BidRequest value) {
        if (bidrequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bidrequest_ = value;
          onChanged();
        } else {
          bidrequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public Builder setBidrequest(
          com.google.openrtb.OpenRtb.BidRequest.Builder builderForValue) {
        if (bidrequestBuilder_ == null) {
          bidrequest_ = builderForValue.build();
          onChanged();
        } else {
          bidrequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public Builder mergeBidrequest(com.google.openrtb.OpenRtb.BidRequest value) {
        if (bidrequestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              bidrequest_ != com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance()) {
            bidrequest_ =
              com.google.openrtb.OpenRtb.BidRequest.newBuilder(bidrequest_).mergeFrom(value).buildPartial();
          } else {
            bidrequest_ = value;
          }
          onChanged();
        } else {
          bidrequestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public Builder clearBidrequest() {
        if (bidrequestBuilder_ == null) {
          bidrequest_ = com.google.openrtb.OpenRtb.BidRequest.getDefaultInstance();
          onChanged();
        } else {
          bidrequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidRequest.Builder getBidrequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getBidrequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidRequestOrBuilder getBidrequestOrBuilder() {
        if (bidrequestBuilder_ != null) {
          return bidrequestBuilder_.getMessageOrBuilder();
        } else {
          return bidrequest_;
        }
      }
      /**
       * <code>optional .com.google.openrtb.BidRequest bidrequest = 1;</code>
       *
       * <pre>
       * Mbr: mbr-bid-request.proto.
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.openrtb.OpenRtb.BidRequest, com.google.openrtb.OpenRtb.BidRequest.Builder, com.google.openrtb.OpenRtb.BidRequestOrBuilder> 
          getBidrequestFieldBuilder() {
        if (bidrequestBuilder_ == null) {
          bidrequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.openrtb.OpenRtb.BidRequest, com.google.openrtb.OpenRtb.BidRequest.Builder, com.google.openrtb.OpenRtb.BidRequestOrBuilder>(
                  getBidrequest(),
                  getParentForChildren(),
                  isClean());
          bidrequest_ = null;
        }
        return bidrequestBuilder_;
      }

      private com.google.openrtb.OpenRtb.BidResponse bidresponse_ = com.google.openrtb.OpenRtb.BidResponse.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.google.openrtb.OpenRtb.BidResponse, com.google.openrtb.OpenRtb.BidResponse.Builder, com.google.openrtb.OpenRtb.BidResponseOrBuilder> bidresponseBuilder_;
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public boolean hasBidresponse() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidResponse getBidresponse() {
        if (bidresponseBuilder_ == null) {
          return bidresponse_;
        } else {
          return bidresponseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public Builder setBidresponse(com.google.openrtb.OpenRtb.BidResponse value) {
        if (bidresponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          bidresponse_ = value;
          onChanged();
        } else {
          bidresponseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public Builder setBidresponse(
          com.google.openrtb.OpenRtb.BidResponse.Builder builderForValue) {
        if (bidresponseBuilder_ == null) {
          bidresponse_ = builderForValue.build();
          onChanged();
        } else {
          bidresponseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public Builder mergeBidresponse(com.google.openrtb.OpenRtb.BidResponse value) {
        if (bidresponseBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              bidresponse_ != com.google.openrtb.OpenRtb.BidResponse.getDefaultInstance()) {
            bidresponse_ =
              com.google.openrtb.OpenRtb.BidResponse.newBuilder(bidresponse_).mergeFrom(value).buildPartial();
          } else {
            bidresponse_ = value;
          }
          onChanged();
        } else {
          bidresponseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public Builder clearBidresponse() {
        if (bidresponseBuilder_ == null) {
          bidresponse_ = com.google.openrtb.OpenRtb.BidResponse.getDefaultInstance();
          onChanged();
        } else {
          bidresponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidResponse.Builder getBidresponseBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getBidresponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      public com.google.openrtb.OpenRtb.BidResponseOrBuilder getBidresponseOrBuilder() {
        if (bidresponseBuilder_ != null) {
          return bidresponseBuilder_.getMessageOrBuilder();
        } else {
          return bidresponse_;
        }
      }
      /**
       * <code>optional .com.google.openrtb.BidResponse bidresponse = 2;</code>
       *
       * <pre>
       * Mbr: mbr-bid-response.proto.
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.openrtb.OpenRtb.BidResponse, com.google.openrtb.OpenRtb.BidResponse.Builder, com.google.openrtb.OpenRtb.BidResponseOrBuilder> 
          getBidresponseFieldBuilder() {
        if (bidresponseBuilder_ == null) {
          bidresponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.openrtb.OpenRtb.BidResponse, com.google.openrtb.OpenRtb.BidResponse.Builder, com.google.openrtb.OpenRtb.BidResponseOrBuilder>(
                  getBidresponse(),
                  getParentForChildren(),
                  isClean());
          bidresponse_ = null;
        }
        return bidresponseBuilder_;
      }

      private eu.m6r.format.openrtb.MbrWin.Win win_ = eu.m6r.format.openrtb.MbrWin.Win.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          eu.m6r.format.openrtb.MbrWin.Win, eu.m6r.format.openrtb.MbrWin.Win.Builder, eu.m6r.format.openrtb.MbrWin.WinOrBuilder> winBuilder_;
      /**
       * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
       *
       * <pre>
       * Mbr: mbr-win.proto.
       * </pre>
       */
      public boolean hasWin() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
       *
       * <pre>
       * Mbr: mbr-win.proto.
       * </pre>
       */
      public eu.m6r.format.openrtb.MbrWin.Win getWin() {
        if (winBuilder_ == null) {
          return win_;
        } else {
          return winBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
       *
       * <pre>
       * Mbr: mbr-win.proto.
       * </pre>
       */
      public Builder setWin(eu.m6r.format.openrtb.MbrWin.Win value) {
        if (winBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          win_ = value;
          onChanged();
        } else {
          winBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
       *
       * <pre>
       * Mbr: mbr-win.proto.
       * </pre>
       */
      public Builder setWin(
          eu.m6r.format.openrtb.MbrWin.Win.Builder builderForValue) {
        if (winBuilder_ == null) {
          win_ = builderForValue.build();
          onChanged();
        } else {
          winBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
       *
       * <pre>
       * Mbr: mbr-win.proto.
       * </pre>
       */
      public Builder mergeWin(eu.m6r.format.openrtb.MbrWin.Win value) {
        if (winBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              win_ != eu.m6r.format.openrtb.MbrWin.Win.getDefaultInstance()) {
            win_ =
              eu.m6r.format.openrtb.MbrWin.Win.newBuilder(win_).mergeFrom(value).buildPartial();
          } else {
            win_ = value;
          }
          onChanged();
        } else {
          winBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
       *
       * <pre>
       * Mbr: mbr-win.proto.
       * </pre>
       */
      public Builder clearWin() {
        if (winBuilder_ == null) {
          win_ = eu.m6r.format.openrtb.MbrWin.Win.getDefaultInstance();
          onChanged();
        } else {
          winBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
       *
       * <pre>
       * Mbr: mbr-win.proto.
       * </pre>
       */
      public eu.m6r.format.openrtb.MbrWin.Win.Builder getWinBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getWinFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
       *
       * <pre>
       * Mbr: mbr-win.proto.
       * </pre>
       */
      public eu.m6r.format.openrtb.MbrWin.WinOrBuilder getWinOrBuilder() {
        if (winBuilder_ != null) {
          return winBuilder_.getMessageOrBuilder();
        } else {
          return win_;
        }
      }
      /**
       * <code>optional .eu.m6r.format.openrtb.Win win = 3;</code>
       *
       * <pre>
       * Mbr: mbr-win.proto.
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          eu.m6r.format.openrtb.MbrWin.Win, eu.m6r.format.openrtb.MbrWin.Win.Builder, eu.m6r.format.openrtb.MbrWin.WinOrBuilder> 
          getWinFieldBuilder() {
        if (winBuilder_ == null) {
          winBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              eu.m6r.format.openrtb.MbrWin.Win, eu.m6r.format.openrtb.MbrWin.Win.Builder, eu.m6r.format.openrtb.MbrWin.WinOrBuilder>(
                  getWin(),
                  getParentForChildren(),
                  isClean());
          win_ = null;
        }
        return winBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:eu.m6r.format.openrtb.JoinedWin)
    }

    static {
      defaultInstance = new JoinedWin(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:eu.m6r.format.openrtb.JoinedWin)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_m6r_format_openrtb_Win_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_m6r_format_openrtb_Win_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_m6r_format_openrtb_JoinedWin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_m6r_format_openrtb_JoinedWin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmbr-win.proto\022\025eu.m6r.format.openrtb\032\020" +
      "mbr-amount.proto\032\025mbr-bid-request.proto\032" +
      "\026mbr-bid-response.proto\032\ropenrtb.proto\"\261" +
      "\001\n\003Win\022/\n\007request\030\001 \001(\0132\036.com.google.ope" +
      "nrtb.BidRequest\022\r\n\005bidid\030\002 \001(\t\0224\n\rcampai" +
      "gnprice\030\003 \001(\0132\035.eu.m6r.format.openrtb.Am" +
      "ount\0224\n\rexchangeprice\030\004 \001(\0132\035.eu.m6r.for" +
      "mat.openrtb.Amount\"\236\001\n\tJoinedWin\0222\n\nbidr" +
      "equest\030\001 \001(\0132\036.com.google.openrtb.BidReq" +
      "uest\0224\n\013bidresponse\030\002 \001(\0132\037.com.google.o",
      "penrtb.BidResponse\022\'\n\003win\030\003 \001(\0132\032.eu.m6r" +
      ".format.openrtb.Win"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.adscale.format.opertb.AmountMessage.getDescriptor(),
          eu.m6r.format.openrtb.MbrBidRequest.getDescriptor(),
          eu.m6r.format.openrtb.MbrBidResponse.getDescriptor(),
          com.google.openrtb.OpenRtb.getDescriptor(),
        }, assigner);
    internal_static_eu_m6r_format_openrtb_Win_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eu_m6r_format_openrtb_Win_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eu_m6r_format_openrtb_Win_descriptor,
        new java.lang.String[] { "Request", "Bidid", "Campaignprice", "Exchangeprice", });
    internal_static_eu_m6r_format_openrtb_JoinedWin_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_eu_m6r_format_openrtb_JoinedWin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eu_m6r_format_openrtb_JoinedWin_descriptor,
        new java.lang.String[] { "Bidrequest", "Bidresponse", "Win", });
    org.adscale.format.opertb.AmountMessage.getDescriptor();
    eu.m6r.format.openrtb.MbrBidRequest.getDescriptor();
    eu.m6r.format.openrtb.MbrBidResponse.getDescriptor();
    com.google.openrtb.OpenRtb.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
