// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mbr-amount.proto

package org.adscale.format.opertb;

public final class AmountMessage {
  private AmountMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AmountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:eu.m6r.format.openrtb.Amount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional double value = 1;</code>
     *
     * <pre>
     * Mbr: Value of money in the set currency.
     * </pre>
     */
    boolean hasValue();
    /**
     * <code>optional double value = 1;</code>
     *
     * <pre>
     * Mbr: Value of money in the set currency.
     * </pre>
     */
    double getValue();

    /**
     * <code>optional string cur = 2;</code>
     *
     * <pre>
     * Mbr: Configured currency.
     * </pre>
     */
    boolean hasCur();
    /**
     * <code>optional string cur = 2;</code>
     *
     * <pre>
     * Mbr: Configured currency.
     * </pre>
     */
    java.lang.String getCur();
    /**
     * <code>optional string cur = 2;</code>
     *
     * <pre>
     * Mbr: Configured currency.
     * </pre>
     */
    com.google.protobuf.ByteString
        getCurBytes();
  }
  /**
   * Protobuf type {@code eu.m6r.format.openrtb.Amount}
   */
  public static final class Amount extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:eu.m6r.format.openrtb.Amount)
      AmountOrBuilder {
    // Use Amount.newBuilder() to construct.
    private Amount(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Amount(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Amount defaultInstance;
    public static Amount getDefaultInstance() {
      return defaultInstance;
    }

    public Amount getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Amount(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              value_ = input.readDouble();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              cur_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.adscale.format.opertb.AmountMessage.internal_static_eu_m6r_format_openrtb_Amount_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.adscale.format.opertb.AmountMessage.internal_static_eu_m6r_format_openrtb_Amount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.adscale.format.opertb.AmountMessage.Amount.class, org.adscale.format.opertb.AmountMessage.Amount.Builder.class);
    }

    public static com.google.protobuf.Parser<Amount> PARSER =
        new com.google.protobuf.AbstractParser<Amount>() {
      public Amount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Amount(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Amount> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int VALUE_FIELD_NUMBER = 1;
    private double value_;
    /**
     * <code>optional double value = 1;</code>
     *
     * <pre>
     * Mbr: Value of money in the set currency.
     * </pre>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional double value = 1;</code>
     *
     * <pre>
     * Mbr: Value of money in the set currency.
     * </pre>
     */
    public double getValue() {
      return value_;
    }

    public static final int CUR_FIELD_NUMBER = 2;
    private java.lang.Object cur_;
    /**
     * <code>optional string cur = 2;</code>
     *
     * <pre>
     * Mbr: Configured currency.
     * </pre>
     */
    public boolean hasCur() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string cur = 2;</code>
     *
     * <pre>
     * Mbr: Configured currency.
     * </pre>
     */
    public java.lang.String getCur() {
      java.lang.Object ref = cur_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cur_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string cur = 2;</code>
     *
     * <pre>
     * Mbr: Configured currency.
     * </pre>
     */
    public com.google.protobuf.ByteString
        getCurBytes() {
      java.lang.Object ref = cur_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cur_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      value_ = 0D;
      cur_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, value_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getCurBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, value_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getCurBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.adscale.format.opertb.AmountMessage.Amount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.adscale.format.opertb.AmountMessage.Amount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.adscale.format.opertb.AmountMessage.Amount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.adscale.format.opertb.AmountMessage.Amount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.adscale.format.opertb.AmountMessage.Amount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.adscale.format.opertb.AmountMessage.Amount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.adscale.format.opertb.AmountMessage.Amount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.adscale.format.opertb.AmountMessage.Amount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.adscale.format.opertb.AmountMessage.Amount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.adscale.format.opertb.AmountMessage.Amount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.adscale.format.opertb.AmountMessage.Amount prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code eu.m6r.format.openrtb.Amount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:eu.m6r.format.openrtb.Amount)
        org.adscale.format.opertb.AmountMessage.AmountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.adscale.format.opertb.AmountMessage.internal_static_eu_m6r_format_openrtb_Amount_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.adscale.format.opertb.AmountMessage.internal_static_eu_m6r_format_openrtb_Amount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.adscale.format.opertb.AmountMessage.Amount.class, org.adscale.format.opertb.AmountMessage.Amount.Builder.class);
      }

      // Construct using org.adscale.format.opertb.AmountMessage.Amount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        value_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        cur_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.adscale.format.opertb.AmountMessage.internal_static_eu_m6r_format_openrtb_Amount_descriptor;
      }

      public org.adscale.format.opertb.AmountMessage.Amount getDefaultInstanceForType() {
        return org.adscale.format.opertb.AmountMessage.Amount.getDefaultInstance();
      }

      public org.adscale.format.opertb.AmountMessage.Amount build() {
        org.adscale.format.opertb.AmountMessage.Amount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.adscale.format.opertb.AmountMessage.Amount buildPartial() {
        org.adscale.format.opertb.AmountMessage.Amount result = new org.adscale.format.opertb.AmountMessage.Amount(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.value_ = value_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.cur_ = cur_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.adscale.format.opertb.AmountMessage.Amount) {
          return mergeFrom((org.adscale.format.opertb.AmountMessage.Amount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.adscale.format.opertb.AmountMessage.Amount other) {
        if (other == org.adscale.format.opertb.AmountMessage.Amount.getDefaultInstance()) return this;
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        if (other.hasCur()) {
          bitField0_ |= 0x00000002;
          cur_ = other.cur_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.adscale.format.opertb.AmountMessage.Amount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.adscale.format.opertb.AmountMessage.Amount) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double value_ ;
      /**
       * <code>optional double value = 1;</code>
       *
       * <pre>
       * Mbr: Value of money in the set currency.
       * </pre>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional double value = 1;</code>
       *
       * <pre>
       * Mbr: Value of money in the set currency.
       * </pre>
       */
      public double getValue() {
        return value_;
      }
      /**
       * <code>optional double value = 1;</code>
       *
       * <pre>
       * Mbr: Value of money in the set currency.
       * </pre>
       */
      public Builder setValue(double value) {
        bitField0_ |= 0x00000001;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double value = 1;</code>
       *
       * <pre>
       * Mbr: Value of money in the set currency.
       * </pre>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object cur_ = "";
      /**
       * <code>optional string cur = 2;</code>
       *
       * <pre>
       * Mbr: Configured currency.
       * </pre>
       */
      public boolean hasCur() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string cur = 2;</code>
       *
       * <pre>
       * Mbr: Configured currency.
       * </pre>
       */
      public java.lang.String getCur() {
        java.lang.Object ref = cur_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cur_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string cur = 2;</code>
       *
       * <pre>
       * Mbr: Configured currency.
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCurBytes() {
        java.lang.Object ref = cur_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cur_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string cur = 2;</code>
       *
       * <pre>
       * Mbr: Configured currency.
       * </pre>
       */
      public Builder setCur(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cur_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string cur = 2;</code>
       *
       * <pre>
       * Mbr: Configured currency.
       * </pre>
       */
      public Builder clearCur() {
        bitField0_ = (bitField0_ & ~0x00000002);
        cur_ = getDefaultInstance().getCur();
        onChanged();
        return this;
      }
      /**
       * <code>optional string cur = 2;</code>
       *
       * <pre>
       * Mbr: Configured currency.
       * </pre>
       */
      public Builder setCurBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        cur_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:eu.m6r.format.openrtb.Amount)
    }

    static {
      defaultInstance = new Amount(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:eu.m6r.format.openrtb.Amount)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eu_m6r_format_openrtb_Amount_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_eu_m6r_format_openrtb_Amount_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020mbr-amount.proto\022\025eu.m6r.format.openrt" +
      "b\"$\n\006Amount\022\r\n\005value\030\001 \001(\001\022\013\n\003cur\030\002 \001(\tB" +
      "*\n\031org.adscale.format.opertbB\rAmountMess" +
      "age"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_eu_m6r_format_openrtb_Amount_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eu_m6r_format_openrtb_Amount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_eu_m6r_format_openrtb_Amount_descriptor,
        new java.lang.String[] { "Value", "Cur", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
